-- CSC Global — yönetim paneli veritabanı şeması (Supabase / Postgres)
-- Güvenlik modeli:
--   * Ziyaretçi (anon): yalnızca aktif ilaçları ve yayındaki blogları OKUR. Yazamaz.
--   * Fiyatlar ayrı tabloda (ilac_fiyatlari); yalnızca admin okur/yazar. Herkese açık sitede asla görünmez.
--   * Admin = public.admins tablosunda kaydı olan Supabase Auth kullanıcısı. Kayıt (signup) kapalı tutulmalı.

-- ---------- Admin listesi ----------
create table if not exists public.admins (
  user_id    uuid primary key references auth.users(id) on delete cascade,
  email      text not null,
  created_at timestamptz not null default now()
);
alter table public.admins enable row level security;
drop policy if exists "admin kendi kaydını görür" on public.admins;
create policy "admin kendi kaydını görür" on public.admins
  for select to authenticated using (user_id = (select auth.uid()));

create or replace function public.is_admin() returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (select 1 from public.admins a where a.user_id = (select auth.uid()));
$$;
revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

create or replace function public.set_updated_at() returns trigger
language plpgsql set search_path = '' as $$
begin new.updated_at = now(); return new; end;
$$;

-- ---------- İlaçlar (herkese açık katalog) ----------
create table if not exists public.ilaclar (
  id            bigint generated by default as identity primary key,
  ad            text not null check (char_length(ad) between 1 and 200),
  etkin_madde   text not null default '-' check (char_length(etkin_madde) <= 300),
  atc_kodu      text not null default '-' check (char_length(atc_kodu) <= 20),
  ruhsat_sahibi text not null default '-' check (char_length(ruhsat_sahibi) <= 120),
  barkod        text not null default '-' check (char_length(barkod) <= 40),
  tedavi_alani  text not null default 'Diğer' check (char_length(tedavi_alani) <= 80),
  form          text not null default 'Diğer' check (char_length(form) <= 60),
  stok          integer check (stok is null or stok >= 0),  -- null = stok bilgisi yok
  aktif         boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
drop trigger if exists ilaclar_updated_at on public.ilaclar;
create trigger ilaclar_updated_at before update on public.ilaclar
  for each row execute function public.set_updated_at();
alter table public.ilaclar enable row level security;
drop policy if exists "aktif ilaçlar herkese açık" on public.ilaclar;
create policy "aktif ilaçlar herkese açık" on public.ilaclar
  for select to anon, authenticated using (aktif or (select public.is_admin()));
drop policy if exists "admin ilaç ekler" on public.ilaclar;
create policy "admin ilaç ekler" on public.ilaclar
  for insert to authenticated with check ((select public.is_admin()));
drop policy if exists "admin ilaç günceller" on public.ilaclar;
create policy "admin ilaç günceller" on public.ilaclar
  for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));
drop policy if exists "admin ilaç siler" on public.ilaclar;
create policy "admin ilaç siler" on public.ilaclar
  for delete to authenticated using ((select public.is_admin()));

-- ---------- İlaç fiyatları (GİZLİ — yalnızca admin) ----------
create table if not exists public.ilac_fiyatlari (
  ilac_id    bigint primary key references public.ilaclar(id) on delete cascade,
  fiyat      numeric(12,2) check (fiyat >= 0),
  updated_at timestamptz not null default now()
);
drop trigger if exists ilac_fiyatlari_updated_at on public.ilac_fiyatlari;
create trigger ilac_fiyatlari_updated_at before update on public.ilac_fiyatlari
  for each row execute function public.set_updated_at();
alter table public.ilac_fiyatlari enable row level security;
revoke all on public.ilac_fiyatlari from anon;
drop policy if exists "fiyatlar yalnızca admin" on public.ilac_fiyatlari;
create policy "fiyatlar yalnızca admin" on public.ilac_fiyatlari
  for all to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));

-- ---------- Blog yazıları (5 dil, icerik = {tr|en|ru|kz|az: {title, excerpt, content[]}}) ----------
create table if not exists public.blog_yazilari (
  id           bigint generated by default as identity primary key,
  kategori     text not null default 'regulations' check (kategori in ('regulations', 'stats', 'trends')),
  tarih        date not null default current_date,
  okuma_suresi integer not null default 5 check (okuma_suresi between 1 and 60),
  gorsel       text not null default '/img-cat-ilac.jpg' check (char_length(gorsel) <= 300),
  icerik       jsonb not null,
  yayinda      boolean not null default true,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
drop trigger if exists blog_yazilari_updated_at on public.blog_yazilari;
create trigger blog_yazilari_updated_at before update on public.blog_yazilari
  for each row execute function public.set_updated_at();
alter table public.blog_yazilari enable row level security;
drop policy if exists "yayındaki bloglar herkese açık" on public.blog_yazilari;
create policy "yayındaki bloglar herkese açık" on public.blog_yazilari
  for select to anon, authenticated using (yayinda or (select public.is_admin()));
drop policy if exists "admin blog yazar" on public.blog_yazilari;
create policy "admin blog yazar" on public.blog_yazilari
  for insert to authenticated with check ((select public.is_admin()));
drop policy if exists "admin blog günceller" on public.blog_yazilari;
create policy "admin blog günceller" on public.blog_yazilari
  for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));
drop policy if exists "admin blog siler" on public.blog_yazilari;
create policy "admin blog siler" on public.blog_yazilari
  for delete to authenticated using ((select public.is_admin()));

create index if not exists blog_yazilari_tarih_idx on public.blog_yazilari (tarih desc);
