import { createContext, useContext, useState, useCallback, type ReactNode } from 'react';

type Language = 'en' | 'tr' | 'ru' | 'kz' | 'az';

interface Translations {
  [key: string]: string;
}

/* ──────────────────────────────────────────────
   EN / TR / RU / KZ — Full translation matrix
   ────────────────────────────────────────────── */

const translations: Record<Language, Translations> = {
  en: {
    /* NAV */
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.products': 'Products',
    'nav.corporate': 'Corporate',
    'nav.contact': 'Contact',
    'nav.about': 'About Us',
    'nav.blog': 'Blog',
    'nav.catalog': 'Catalog',
    'nav.whatsapp': 'WhatsApp',
    /* HERO */
    'hero.title': 'Reliable Medicine Supply from Türkiye to the World',
    'hero.subtitle': 'We deliver Turkish-origin medicines to international pharmaceutical warehouses with high standards and fast delivery service.',
    'hero.cta': 'Explore Warehouse Services',
    'hero.cta2': 'Contact Us',
    'hero.scroll': 'Scroll Down',
    /* SERVICES */
    'services.label': '',
    'services.title': 'Our Services',
    'services.subtitle': 'At every stage of pharmaceutical warehousing, we offer Ministry of Health approved and GDP compliant services.',
    'service.storage.title': 'Storage Services',
    'service.storage.desc': 'We safely store your medicines in our Ministry of Health approved facilities. 2-8°C cold chain storage, ambient temperature areas, and quarantine sections with fully integrated solutions.',
    'service.storage.chips': '2-8°C Storage,Quarantine Area,Ambient Temp',
    'service.logistics.title': 'Logistics & Distribution',
    'service.logistics.desc': 'Reliable Türkiye-to-world pharmaceutical transport. GDP compliant vehicle fleet, temperature monitoring systems, and door-to-door delivery.',
    'service.logistics.chips': 'GDP Fleet,Door-to-Door,Temp Monitoring',
    'service.coldchain.title': 'Cold Chain Management',
    'service.coldchain.desc': 'We deliver your medicines without breaking the cold chain with special containers and monitoring systems in the 2-8°C range.',
    'service.coldchain.chips': '2-8°C Containers,24/7 Monitoring,Cold Chain',
    'service.digital.title': 'Digital Supply Platform',
    'service.digital.desc': 'Manage all processes digitally with web-based order management, stock tracking, online reporting, and information flow.',
    'service.digital.chips': 'Order Mgmt,Stock Tracking,Online Reports',
    'service.supply.title': 'Supply Chain Solutions',
    'service.supply.desc': 'Planning, optimization, and management of all processes from manufacturer to end consumer. Inventory optimization and emergency shipments.',
    'service.supply.chips': 'Inventory Mgmt,Emergency Ship,Lot Tracking',
    'service.bulk.title': 'Bulk Supply Services',
    'service.bulk.desc': 'Bulk ordering for pharmacies and hospitals. Cost advantages, consistent supply, and coordinated distribution solutions.',
    'service.bulk.chips': 'Bulk Orders,Cost Advantage,Coordinated Dist.',
    /* STATS */
    'stats.label': '',
    'stats.title': 'CSC in Numbers',
    'stats.pharmacies': 'Pharmacies Supplied',
    'stats.pharmacies.detail': 'Pharmacy network worldwide',
    'stats.brands': 'Global Medicine Brands',
    'stats.brands.detail': 'Trusted manufacturers worldwide',
    'stats.temp': 'Cold Chain Range',
    'stats.temp.detail': '24/7 temperature monitoring',
    'stats.experience': 'Years of Experience',
    'stats.experience.detail': 'Ministry of Health approved',
    'stats.badge': 'Ministry of Health Approved | GDP Compliant',
    'stats.badge.sub': 'Good Distribution Practice',
    /* COLD CHAIN */
    'coldchain.label': '',
    'coldchain.title': 'Cold Chain, Warm Trust',
    'coldchain.body': 'We never break the cold chain for the integrity of your medicines. With 2-8°C temperature insulated containers and 24/7 digital temperature monitoring, every step is recorded. GDP compliant logistics solutions throughout the process from Türkiye to the world.',
    'coldchain.feat1': '24/7 Temperature Monitoring',
    'coldchain.feat2': 'GPS Vehicle Tracking',
    'coldchain.feat3': 'GDP Compliant Transport',
    'coldchain.live': 'Cold Chain Active | 4.2°C',
    /* PRODUCTS (homepage section) */
    'products.label': '',
    'products.title': 'Product Portfolio',
    'products.subtitle': 'Comprehensive pharmaceutical and medical product categories for healthcare institutions worldwide.',
    'product.dialysis.title': 'Peritoneal Dialysis Solutions',
    'product.dialysis.desc': 'Physioneal, Extraneal, Nutrineal and more. Official supplier of peritoneal dialysis solutions from world leaders like Baxter and Fresenius.',
    'product.supplies.title': 'Auxiliary Materials',
    'product.supplies.desc': 'Complete range of sets, containers, connection parts, and other auxiliary materials used in peritoneal dialysis treatment.',
    'product.devices.title': 'Medical Devices & Equipment',
    'product.devices.desc': 'Diagnostic and treatment devices, monitors, infusion pumps, and other medical equipment specialized for the healthcare sector.',
    /* PRODUCT CATEGORIES */
    'prodcat.title': 'Product Categories',
    'prodcat.subtitle': 'Reliable supply in all product groups needed by the healthcare sector.',
    'prodcat.ilac.title': 'Pharmaceutical Products',
    'prodcat.ilac.desc': 'Comprehensive portfolio from antibiotics to pain relievers, cardiovascular to dermatological products.',
    'prodcat.ilac.btn': 'Explore',
    'prodcat.gida.title': 'Food Supplements',
    'prodcat.gida.desc': 'Vitamins, minerals, probiotics, omega-3 and herbal supplements.',
    'prodcat.gida.btn': 'Explore',
    'prodcat.sarf.title': 'Medical Supplies',
    'prodcat.sarf.desc': 'Wound care products, surgical supplies, IV products and diagnostic materials.',
    'prodcat.sarf.btn': 'Explore',
    'prodcat.bebek.title': 'Patient & Baby Diapers',
    'prodcat.bebek.desc': 'Adult diapers, absorbent pads, baby diapers and stoma products.',
    'prodcat.bebek.btn': 'Explore',
    'prodcat.cihaz.title': 'Medical Devices',
    'prodcat.cihaz.desc': 'Nebulizers, blood pressure monitors, glucometers and medical devices.',
    'prodcat.cihaz.btn': 'Explore',
    'prodcat.test.title': 'Medical Tests',
    'prodcat.test.desc': 'Rapid diagnostic tests, pregnancy tests, blood glucose strips and more.',
    'prodcat.test.btn': 'Explore',
    /* TRUST */
    'trust.label': '',
    'trust.title': 'Trust & Certificates',
    'trust.subtitle': 'We carry out all our activities at the highest quality and safety standards, in full compliance with legal regulations.',
    'cert.ministry.title': 'Ministry of Health Approved',
    'cert.ministry.desc': 'Medicine warehouse license approved and supervised by the Ministry of Health.',
    'cert.gdp.title': 'GDP Compliance',
    'cert.gdp.desc': 'We manage all processes under Good Distribution Practice.',
    'cert.coldchain.title': 'Cold Chain Certification',
    'cert.coldchain.desc': 'Special certification and monitoring systems for storage and transport in the 2-8°C range.',
    'cert.quality.title': 'Quality Control & Lot Tracking',
    'cert.quality.desc': 'Computer-based recording and tracking of product acceptance, stock, and shipment processes with barcode system.',
    'trust.compliance': 'The expiry and lot tracking of all our products is recorded from stock to shipment via barcode system. We implement cold chain, hygiene, and safety standards at the highest level in accordance with Ministry of Health procedures.',
    /* PROCESS */
    'process.label': '',
    'process.title': 'How It Works?',
    'process.subtitle': 'Reliable pharmaceutical supply in 4 steps through our digital platform.',
    'process.step1.title': 'Place Your Order',
    'process.step1.desc': 'Create your order through our web-based platform or by contacting us directly.',
    'process.step2.title': 'Approval & Preparation',
    'process.step2.desc': 'Your order is approved by our responsible pharmacist, quality controlled, and prepared.',
    'process.step3.title': 'Logistics & Shipment',
    'process.step3.desc': 'We dispatch medicines with GDP compliant vehicles and temperature monitoring systems.',
    'process.step4.title': 'Doorstep Delivery',
    'process.step4.desc': 'Your medicines are delivered to your address under hygienic conditions with barcode control.',
    /* CONTACT */
    'contact.label': '',
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Our team at our offices will be happy to assist you.',
    'contact.az.title': 'CSC AZ — Baku Office',
    'contact.az.address': 'BAKI CITY, BINEQEDI DISTRICT, HEMZE BABASOV STREET, 9TH MKR, BUILDING 1, APT 1',
    'contact.tr.title': 'CSC-TR — Istanbul Office',
    'contact.tr.address': 'Kayabasi Mah. Sogutozu Sokak, Basaksehir, Istanbul, Türkiye',
    'contact.email': 'info@csc-tr.com',
    'contact.web': 'csc-tr.com',
    'contact.whatsapp.btn': 'Write on WhatsApp',
    'contact.emailbtn': 'Send Email',
    'contact.note': '*Contact us for detailed information about our pharmaceutical warehouse services.',
    'contact.form.name': 'First Name',
    'contact.form.surname': 'Last Name',
    'contact.form.email': 'Email',
    'contact.form.message': 'Message',
    'contact.form.submit': 'Send Message',
    'contact.form.success': 'Your message has been sent successfully!',
    /* FOOTER */
    'footer.tagline': 'CSC-TR and CSC-AZ, a pharmaceutical warehouse and medicine supply chain platform that delivers Turkish-origin medicines to healthcare institutions worldwide reliably and quickly.',
    'footer.services': 'Services',
    'footer.products': 'Products',
    'footer.branches': 'Branches',
    'footer.contact': 'Contact',
    'footer.bottom': '\u00A9 2025 CSC Pharmaceutical Warehouse. All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Use',
    'footer.gdp': 'GDP Compliance',
    'footer.cookie': 'Cookie Policy',
    'footer.kvkk': 'KVKK Notice',
    /* MODAL */
    'modal.title': 'Healthcare Professional Confirmation',
    'modal.text': 'Attention! This section is designed exclusively for healthcare professionals. If you are not a healthcare professional, you can return to the homepage by selecting "No".',
    'modal.yes': 'Yes, I am a healthcare professional',
    'modal.no': 'No, return to homepage',
    'modal.warning': 'This section contains pharmaceutical product information intended only for healthcare professionals.',
    /* PAGE TITLES */
    'products.page.title': 'Pharmaceutical Products',
    'products.page.subtitle': 'Browse our comprehensive range of pharmaceutical products. Healthcare professional verification required.',
    'products.filter.all': 'All',
    'products.filter.pain': 'Pain Relievers',
    'products.filter.antibiotics': 'Antibiotics',
    'products.filter.coldchain': 'Cold Chain',
    'products.filter.dermatology': 'Dermatology',
    'products.filter.cardio': 'Cardiovascular',
    'products.filter.respiratory': 'Respiratory',
    'products.filter.dialysis': 'Dialysis',
    'products.search': 'Search Products...',
    'products.alpha': 'ABCDEFGHIJKLMNOPQRSTUVWXYZ',
    'products.category': 'Category',
    'products.brand': 'Brand',
    'products.view': 'View',
    'services.page.title': 'Our Services',
    'services.page.subtitle': 'Comprehensive pharmaceutical warehousing and distribution solutions.',
    'branches.title': 'Global Locations',
    'branches.subtitle': 'CSC-TR Istanbul Headquarters — CSC-AZ Azerbaijan Branch. Kazakhstan expansion planned for the future.',
    'branches.tr.label': 'HEADQUARTERS',
    'branches.tr.name': 'CSC-TR Ecza Deposu',
    'branches.tr.location': 'Istanbul, Türkiye',
    'branches.az.label': 'BRANCH',
    'branches.az.name': 'CSC-AZ Pharmaceutical Warehouse',
    'branches.az.location': 'Baku, Azerbaijan',
    'branches.kz.label': 'COMING SOON',
    'branches.kz.name': 'CSC-KZ Pharmaceutical Warehouse',
    'branches.kz.location': 'Kazakhstan (Planned)',
    'blog.title': 'Pharma Insights Blog',
    'blog.subtitle': 'Latest developments in pharmaceutical exports, import regulations, and healthcare trends across Central Asia, Caucasus, and Africa.',
    'blog.read': 'Read More',
    'blog.close': 'Close',
    'blog.category.all': 'All',
    'blog.category.stats': 'Market Statistics',
    'blog.category.regulations': 'Regulations',
    'blog.category.trends': 'Industry Trends',
    'catalog.title': 'Product Catalog',
    'catalog.subtitle': 'Browse our comprehensive product catalog. PDF version coming soon.',
    'catalog.coming': 'Our detailed product catalog will be available for download soon. Contact us for immediate product inquiries.',
    'lang.en': 'EN',
    'lang.tr': 'TR',
    'lang.ru': 'RU',
    'lang.kz': 'KZ',
    'marquee.partners': 'Global Medicine Partners',
    'marquee.label': 'TURKISH PRODUCERS',
    'marquee.title': 'Türkiye-Based Pharmaceutical Manufacturers',
    /* COOKIE */
    'cookie.text': 'We use cookies to improve your experience. By continuing, you agree to our ',
    'cookie.privacy': 'Privacy Policy',
    'cookie.accept': 'Accept',
    'cookie.reject': 'Reject',
    /* LEGAL PAGES */
    'legal.lastupdated': 'Last updated',
    'privacy.title': 'Privacy Policy',
    'terms.title': 'Terms of Use',
    'cookiepolicy.title': 'Cookie Policy',
    'kvkk.title': 'KVKK Disclosure Statement',
    'about.title': 'About Us',
    'about.values.title': 'Our Values',
    'about.values.year': 'CSC has been operating with a total pharmaceutical purchase and sales license since 2016.',
    'about.values.intro': 'CSC is the three whales on which all our work keeps. CLIENTS, SOLUTIONS and CARE.',
    'about.values.gear': 'It is similar to the main gear wheels in the huge mechanism these concepts convey and bring our actions.',
    'corporate.tab.about': 'About',
    'corporate.tab.mission': 'Mission',
    'corporate.tab.vision': 'Vision',
    'corporate.tab.branches': 'Branches',
    'corporate.tab.certificates': 'Certificates',
    'corporate.tab.team': 'Team',
    'corporate.clients.title': 'Clients',
    'corporate.clients.slogan': 'Keep the word!',
    'corporate.solutions.title': 'Solutions',
    'corporate.solutions.slogan': 'Find Solutions!',
    'corporate.care.title': 'Care',
    'corporate.care.slogan': 'Take Care!',
    'corporate.clients.desc': 'We keep our word – we put the interests of business and partners above our own, responsibly give promises\n\nOur word is the word given by each member of the team.\n\nWe are honest and do not hide the problem.\n\nWe provide only reliable information.\n\nA client is a doctor, a pharmacy, a partner, a manufacturer.',
    'corporate.solutions.desc': 'We find a solution – we combine enterprise, creativity and innovation, take the initiative in the face of a problem, set interesting ambitious goals, strive to develop ourselves, business and processes.\n\nWe solve problems by command.\n\nRecognize the merits of others. We encourage attempts to make a new one. We forgive the mistakes of others, are ruthless towards themselves.',
    'corporate.care.desc': 'We care about consumers of our products – we have expert knowledge of our products, we understand the needs of patients.\n\nWe are looking for new products that even better solve the problems of patients, and ensure their availability.\n\nWe care about the training of doctors, about the safe and convenient use of our products.\n\nWe develop services for patients and doctors.',
    'corporate.mission.title': 'Our Mission',
    'corporate.mission.body': 'To deliver high-quality, Turkish-origin pharmaceuticals to healthcare institutions worldwide with reliability, speed, and full regulatory compliance. We aim to be the most trusted pharmaceutical supply partner in Central Asia, Caucasus, Africa and beyond, bridging Turkish manufacturers with global markets.',
    'corporate.vision.title': 'Our Vision',
    'corporate.vision.body': 'To become the premier pharmaceutical distribution network connecting Turkish pharmaceutical manufacturers with global markets. By 2028, we aim to operate in 50+ countries with a fully integrated cold chain network, digital supply platform, and local partnerships across four continents.',
    'corporate.team.title': 'Our Leadership Team',
    'corporate.team.body': 'Our team consists of experienced pharmacists, logistics specialists, and regulatory experts. With over 10 years of pharmaceutical supply chain experience, we ensure every shipment meets the highest quality standards.',
    'corporate.title': 'Corporate',
    'corporate.subtitle': 'Learn about CSC Pharmaceutical Warehouse in detail.',


  },
  tr: {
    'nav.home': 'Anasayfa',
    'nav.services': 'Hizmetler',
    'nav.products': '\u00DCr\u00FCnler',
    'nav.corporate': 'Kurumsal',
    'nav.contact': '\u0130leti\u015Fim',
    'nav.about': 'Hakk\u0131m\u0131zda',
    'nav.blog': 'Blog',
    'nav.catalog': 'Katalog',
    'nav.whatsapp': 'WhatsApp',
    'hero.title': 'T\u00FCrkiye\'den Yurtd\u0131\u015F\u0131na G\u00FCvenilir \u0130la\u00E7 Tedari\u011Fi',
    'hero.subtitle': 'T\u00FCrkiye men\u015Feli ila\u00E7lar\u0131 y\u00FCksek standartlarda ve h\u0131zl\u0131 teslimat hizmetiyle yurtd\u0131\u015F\u0131 ecza depolar\u0131na ula\u015Ft\u0131r\u0131yoruz.',
    'hero.cta': 'Depo Hizmetlerini \u0130ncele',
    'hero.cta2': 'Bize Ula\u015F\u0131n',
    'hero.scroll': 'A\u015Fa\u011F\u0131 Kayd\u0131r',
    'services.label': '',
    'services.title': 'Hizmetlerimiz',
    'services.subtitle': 'Ecza depoculu\u011Funun her a\u015Famas\u0131nda, Sa\u011Fl\u0131k Bakanl\u0131\u011F\u0131 onayl\u0131 ve GDP uyumlu hizmetler sunuyoruz.',
    'service.storage.title': 'Depolama Hizmetleri',
    'service.storage.desc': 'Sa\u011Fl\u0131k Bakanl\u0131\u011F\u0131 onayl\u0131 depolama alanlar\u0131m\u0131zda ila\u00E7lar\u0131n\u0131z\u0131 g\u00FCvenle muhafaza ediyoruz. 2-8\u00B0C so\u011Fuk zincir depolama, oda s\u0131cakl\u0131\u011F\u0131 alanlar\u0131 ve karantina b\u00F6lmeleri ile tam entegre \u00E7\u00F6z\u00FCmler.',
    'service.storage.chips': '2-8\u00B0C Depolama,Karantina Alan\u0131,Oda S\u0131cakl\u0131\u011F\u0131',
    'service.logistics.title': 'Lojistik ve Da\u011F\u0131t\u0131m',
    'service.logistics.desc': 'T\u00FCrkiye-yurtd\u0131\u015F\u0131 aras\u0131 g\u00FCvenilir ila\u00E7 ta\u015F\u0131mac\u0131l\u0131\u011F\u0131. GDP uyumlu ara\u00E7 filosu, s\u0131cakl\u0131k izleme sistemleri ve kap\u0131ya teslimat.',
    'service.logistics.chips': 'GDP Filo,Kap\u0131ya Teslimat,S\u0131cakl\u0131k \u0130zleme',
    'service.coldchain.title': 'So\u011Fuk Zincir Y\u00F6netimi',
    'service.coldchain.desc': '2-8\u00B0C s\u0131cakl\u0131k aral\u0131\u011F\u0131nda \u00F6zel kaplar ve izleme sistemleri ile so\u011Fuk zincir k\u0131rmadan ila\u00E7lar\u0131n\u0131z\u0131 ula\u015Ft\u0131r\u0131yoruz.',
    'service.coldchain.chips': '2-8\u00B0C Konteyner,7/24 \u0130zleme,So\u011Fuk Zincir',
    'service.digital.title': 'Dijital Tedarik Platformu',
    'service.digital.desc': 'Web tabanl\u0131 sipari\u015F y\u00F6netimi, stok takibi, online raporlama ve bilgi ak\u0131\u015F\u0131 ile t\u00FCm s\u00FCre\u00E7leri dijital ortamda y\u00F6netin.',
    'service.digital.chips': 'Sipari\u015F Y\u00F6netimi,Stok Takibi,Online Raporlama',
    'service.supply.title': 'Tedarik Zinciri \u00C7\u00F6z\u00FCmleri',
    'service.supply.desc': '\u00Dcreticiden nihai t\u00FCketiciye kadar t\u00FCm s\u00FCre\u00E7lerin planlanmas\u0131, optimizasyonu ve y\u00F6netimi. Envanter optimizasyonu ve acil \u00FCr\u00FCn sevkiyat\u0131.',
    'service.supply.chips': 'Envanter Y\u00F6netimi,Acil Sevkiyat,Lot Takibi',
    'service.bulk.title': 'Toplu Tedarik Hizmetleri',
    'service.bulk.desc': 'Eczaneler ve hastaneler i\u00E7in toplu sipari\u015F imkan\u0131. Maliyet avantaj\u0131, tutarl\u0131 arz ve koordineli da\u011F\u0131t\u0131m \u00E7\u00F6z\u00FCmleri.',
    'service.bulk.chips': 'Toplu Sipari\u015F,Maliyet Avantaj\u0131,Koordineli Da\u011F\u0131t\u0131m',
    'stats.label': '',
    'stats.title': 'Rakamlarla CSC',
    'stats.pharmacies': 'Eczaneye Tedarik',
    'stats.pharmacies.detail': 'D\u00FCnya genelinde eczane a\u011F\u0131',
    'stats.brands': 'Global \u0130la\u00E7 Markas\u0131',
    'stats.brands.detail': 'D\u00FCnya \u00E7ap\u0131nda g\u00FCvenilir \u00FCreticiler',
    'stats.temp': 'So\u011Fuk Zincir Aral\u0131\u011F\u0131',
    'stats.temp.detail': '7/24 s\u0131cakl\u0131k izleme ve kay\u0131t',
    'stats.experience': 'Y\u0131ll\u0131k Sekt\u00F6r Tecr\u00FCbesi',
    'stats.experience.detail': 'Sa\u011Fl\u0131k Bakanl\u0131\u011F\u0131 onayl\u0131 operasyon',
    'stats.badge': 'T.C. Sa\u011Fl\u0131k Bakanl\u0131\u011F\u0131 Onayl\u0131 | GDP Uyumlu',
    'stats.badge.sub': 'Good Distribution Practice \u2014 \u0130yi Da\u011F\u0131t\u0131m Uygulamalar\u0131',
    'coldchain.label': '',
    'coldchain.title': 'So\u011Fuk Zincir, S\u0131cak G\u00FCven',
    'coldchain.body': '\u0130la\u00E7lar\u0131n\u0131z\u0131n sa\u011Flaml\u0131\u011F\u0131 i\u00E7in so\u011Fuk zinciri hi\u00E7bir zaman k\u0131rm\u0131yoruz. 2-8\u00B0C s\u0131cakl\u0131k aral\u0131\u011F\u0131nda \u00F6zel izolasyonlu kaplar ve 7/24 dijital s\u0131cakl\u0131k izleme sistemleri ile her ad\u0131m kay\u0131t alt\u0131nda. T\u00FCrkiye\'den d\u00fcnyaya t\u00fcm s\u00fcre\u00e7 boyunca GDP uyumlu lojistik \u00e7\u00f6z\u00fcmler.',
    'coldchain.feat1': '7/24 S\u0131cakl\u0131k \u0130zleme',
    'coldchain.feat2': 'GPS Ara\u00E7 Takibi',
    'coldchain.feat3': 'GDP Uyumlu Ta\u015F\u0131ma',
    'coldchain.live': 'So\u011Fuk Zincir Aktif | 4.2\u00B0C',
    'products.label': '',
    'products.title': '\u00DCr\u00FCn Portf\u00F6y\u00FC',
    'products.subtitle': 'Periton Diyalizi ve sa\u011Fl\u0131k \u00FCr\u00FCnlerinde, d\u00FCnyan\u0131n \u00F6nc\u00FC markalar\u0131n\u0131 g\u00FCvenle tedarik ediyoruz.',
    'product.dialysis.title': 'Periton Diyalizi Sol\u00FCsyonlar\u0131',
    'product.dialysis.desc': 'Physioneal, Extraneal, Nutrineal ve daha fazlas\u0131. Baxter, Fresenius gibi d\u00fcnya devlerinin periton diyalizi \u00E7\u00F6zeltilerinin resmi tedarik\u00E7isi.',
    'product.supplies.title': 'Yard\u0131mc\u0131 Malzemeler',
    'product.supplies.desc': 'Periton diyalizi tedavisinde kullan\u0131lan setler, kaplar, ba\u011Flant\u0131 par\u00E7alar\u0131 ve di\u011Fer yard\u0131mc\u0131 malzemelerin tamam\u0131.',
    'product.devices.title': 'Medikal Cihazlar ve Ekipman',
    'product.devices.desc': 'Tan\u0131 ve tedavi cihazlar\u0131, monit\u00F6rler, inf\u00FCzyon pompalar\u0131 ve sa\u011Fl\u0131k sekt\u00F6r\u00FCne \u00F6zel di\u011Fer medikal ekipmanlar.',
    'prodcat.title': '\u00DCr\u00FCn Kategorilerimiz',
    'prodcat.subtitle': 'Sa\u011Fl\u0131k sekt\u00F6r\u00fcn\u00fcn ihtiya\u00E7 duydu\u011Fu t\u00fcm \u00fcr\u00fcn gruplar\u0131nda g\u00fcvenilir tedarik.',
    'prodcat.ilac.title': '\u0130la\u00E7 \u00DCr\u00FCnleri',
    'prodcat.ilac.desc': 'Antibiyotiklerden a\u011Fr\u0131 kesicilere, kardiyovask\u00fcler ila\u00e7lardan dermatolojik \u00fcr\u00fcnlere geni\u015f portf\u00f6y.',
    'prodcat.ilac.btn': '\u0130ncele',
    'prodcat.gida.title': 'G\u0131da Takviyeleri',
    'prodcat.gida.desc': 'Vitaminler, mineraller, probiyotikler, omega-3 ve bitkisel takviyeler.',
    'prodcat.gida.btn': '\u0130ncele',
    'prodcat.sarf.title': 'T\u0131bbi Sarf Malzemeleri',
    'prodcat.sarf.desc': 'Yara bak\u0131m \u00fcr\u00fcnleri, cerrahi sarf, IV \u00fcr\u00fcnleri ve tan\u0131 malzemeleri.',
    'prodcat.sarf.btn': '\u0130ncele',
    'prodcat.bebek.title': 'Hasta ve Bebek Bezleri',
    'prodcat.bebek.desc': 'Hasta bezleri, emici pedler, bebek bezleri ve stoma \u00fcr\u00fcnleri.',
    'prodcat.bebek.btn': '\u0130ncele',
    'prodcat.cihaz.title': 'T\u0131bbi Cihazlar',
    'prodcat.cihaz.desc': 'Neb\u00fclizat\u00f6rler, tansiyon aletleri, glukometreler ve medikal cihazlar.',
    'prodcat.cihaz.btn': '\u0130ncele',
    'prodcat.test.title': 'T\u0131bbi Testler',
    'prodcat.test.desc': 'H\u0131zl\u0131 tan\u0131 testleri, gebelik testleri, kan \u015fekeri \u015feritleri ve daha fazlas\u0131.',
    'prodcat.test.btn': '\u0130ncele',
    'trust.label': '',
    'trust.title': 'G\u00fcven ve Sertifikalar',
    'trust.subtitle': 'T\u00fcm faaliyetlerimizi en y\u00fcksek kalite ve g\u00fcvenlik standartlar\u0131nda, yasal mevzuatlara tam uyum i\u00e7inde ger\u00e7ekle\u015ftiriyoruz.',
    'cert.ministry.title': 'Sa\u011Fl\u0131k Bakanl\u0131\u011F\u0131 Onayl\u0131',
    'cert.ministry.desc': 'T.C. Sa\u011Fl\u0131k Bakanl\u0131\u011F\u0131 taraf\u0131ndan onaylanan ve denetlenen ecza deposu ruhsat\u0131.',
    'cert.gdp.title': 'GDP Uygunluk',
    'cert.gdp.desc': 'Good Distribution Practice \u2014 \u0130yi Da\u011F\u0131t\u0131m Uygulamalar\u0131 kapsam\u0131nda t\u00fcm s\u00fcre\u00e7leri y\u00f6netiyoruz.',
    'cert.coldchain.title': 'So\u011Fuk Zincir Sertifikasyonu',
    'cert.coldchain.desc': '2-8\u00B0C s\u0131cakl\u0131k aral\u0131\u011F\u0131nda depolama ve ta\u015F\u0131mac\u0131l\u0131k i\u00E7in \u00F6zel sertifikasyon ve izleme sistemleri.',
    'cert.quality.title': 'Kalite Kontrol ve Lot Takibi',
    'cert.quality.desc': 'Karekod sistemi ile \u00fcr\u00fcn kabul, stok ve sevkiyat s\u00fcre\u00e7lerinin bilgisayar ortam\u0131nda kay\u0131t ve takibi.',
    'trust.compliance': 'T\u00fcm \u00fcr\u00fcnlerimizin miyad ve lot takibi, karekod sistemi ile stoktan sevkiyata kadar kay\u0131t alt\u0131ndad\u0131r. Sa\u011Fl\u0131k Bakanl\u0131\u011F\u0131 prosed\u00fcrlerine g\u00f6re so\u011fuk zincir, hijyen ve g\u00fcvenlik standartlar\u0131n\u0131 en \u00fcst d\u00fczeyde uyguluyoruz.',
    'process.label': '',
    'process.title': 'Nas\u0131l \u00C7al\u0131\u015F\u0131r?',
    'process.subtitle': 'Dijital platformumuz \u00fczerinden 4 ad\u0131mda g\u00fcvenilir ila\u00e7 tedarigi.',
    'process.step1.title': 'Sipari\u015F Verin',
    'process.step1.desc': 'Web tabanl\u0131 platformumuz \u00fczerinden veya do\u011Frudan ileti\u015Fime ge\u00E7erek sipari\u015Finizi olu\u015Fturun.',
    'process.step2.title': 'Onay ve Haz\u0131rlama',
    'process.step2.desc': 'Sipari\u015Finiz eczac\u0131 mesul m\u00fcd\u00fcr\u00fcm\u00fcz\u00fcn onay\u0131ndan ge\u00e7er, kalite kontrol\u00fc yap\u0131l\u0131r ve haz\u0131rlan\u0131r.',
    'process.step3.title': 'Lojistik ve Sevkiyat',
    'process.step3.desc': 'GDP uyumlu ara\u00e7larla, s\u0131cakl\u0131k izleme sistemleri e\u015Flili\u011Finde ila\u00e7lar\u0131 yola \u00e7\u0131kar\u0131yoruz.',
    'process.step4.title': 'Kap\u0131n\u0131za Teslimat',
    'process.step4.desc': '\u0130la\u00e7lar\u0131n\u0131z hijyen ko\u015fullar\u0131nda, karekod kontrol\u00fc yap\u0131larak adresinize teslim edilir.',
    'contact.label': '',
    'contact.title': 'Bize Ula\u015F\u0131n',
    'contact.subtitle': 'Azerbaycan ve T\u00fcrkiye\'deki ofislerimizden ekibimiz size yard\u0131mc\u0131 olmaktan memnuniyet duyacakt\u0131r.',
    'contact.az.title': 'CSC AZ \u2014 Bak\u00fc Ofisi',
    'contact.az.address': 'BAK\u00dc \u015e\u018fH\u018fR\u0130, B\u0130N\u018fQ\u018fD\u0130 RAYONU, H\u018fMZ\u018f BABA\u015eOV K\u00dc\u00c7\u018fS\u0130, 9 MKR, EV 1, D\u00d6NG\u018f 1',
    'contact.tr.title': 'CSC-TR \u2014 \u0130stanbul Ofisi',
    'contact.tr.address': 'Kayaba\u015F\u0131 Mah. S\u00f6\u011f\u00fct\u00f6z\u00fc Sokak, Ba\u015fak\u015fehir, \u0130stanbul',
    'contact.email': 'info@csc-tr.com',
    'contact.web': 'csc-tr.com',
    'contact.whatsapp.btn': 'WhatsApp\'tan Yaz\u0131n',
    'contact.emailbtn': 'E-posta G\u00f6nderin',
    'contact.note': '*Ecza depo hizmetlerimiz hakk\u0131nda detayl\u0131 bilgi almak i\u00e7in ileti\u015Fime ge\u00e7in.',
    'contact.form.name': 'Ad',
    'contact.form.surname': 'Soyad',
    'contact.form.email': 'E-posta',
    'contact.form.message': 'Mesaj',
    'contact.form.submit': 'G\u00f6nder',
    'contact.form.success': 'Mesaj\u0131n\u0131z ba\u015far\u0131yla g\u00f6nderildi!',
    'footer.tagline': 'CSC-TR ve CSC-AZ, T\u00fcrkiye men\u015feli ila\u00e7lar\u0131 d\u00fcnyadaki sa\u011fl\u0131k kurulu\u015flar\u0131na g\u00fcvenilir ve h\u0131zl\u0131 \u015fekilde ula\u015ft\u0131ran ecza deposu ve ila\u00e7 tedarik zinciri platformu.',
    'footer.services': 'Hizmetler',
    'footer.products': '\u00dcr\u00fcnler',
    'footer.branches': '\u015eubeler',
    'footer.contact': '\u0130leti\u015fim',
    'footer.bottom': '\u00a9 2025 CSC Ecza Deposu. T\u00fcm haklar\u0131 sakl\u0131d\u0131r.',
    'footer.privacy': 'Gizlilik Politikas\u0131',
    'footer.terms': 'Kullan\u0131m \u015eartlar\u0131',
    'footer.gdp': 'GDP Uygunluk',
    'footer.cookie': '\u00c7erez Politikas\u0131',
    'footer.kvkk': 'KVKK Ayd\u0131nlatma Metni',
    'modal.title': 'Sa\u011fl\u0131k \u00c7al\u0131\u015fan\u0131 Onay\u0131',
    'modal.text': 'Dikkat! Bu b\u00f6l\u00fcm yaln\u0131zca sa\u011fl\u0131k \u00e7al\u0131\u015fanlar\u0131 i\u00e7in tasarlanm\u0131\u015ft\u0131r. Sa\u011fl\u0131k \u00e7al\u0131\u015fan\u0131 de\u011filseniz \u201cHay\u0131r\u201d se\u00e7ene\u011fi ile anasayfaya d\u00f6nebilirsiniz.',
    'modal.yes': 'Evet, sa\u011fl\u0131k \u00e7al\u0131\u015fan\u0131y\u0131m',
    'modal.no': 'Hay\u0131r, anasayfaya d\u00f6n',
    'modal.warning': 'Bu b\u00f6l\u00fcm sadece sa\u011fl\u0131k \u00e7al\u0131\u015fanlar\u0131na y\u00f6nelik ila\u00e7 bilgileri i\u00e7ermektedir.',
    'products.page.title': '\u0130la\u00e7 \u00dcr\u00fcnleri',
    'products.page.subtitle': 'Kapsaml\u0131 ila\u00e7 \u00fcr\u00fcn yelpazemizi inceleyin. Sa\u011fl\u0131k \u00e7al\u0131\u015fan\u0131 do\u011frulamas\u0131 gereklidir.',
    'products.filter.all': 'T\u00fcm\u00fc',
    'products.filter.pain': 'A\u011fr\u0131 Kesiciler',
    'products.filter.antibiotics': 'Antibiyotikler',
    'products.filter.coldchain': 'So\u011fuk Zincir',
    'products.filter.dermatology': 'Dermatoloji',
    'products.filter.cardio': 'Kardiyovask\u00fcler',
    'products.filter.respiratory': 'Solunum Sistemi',
    'products.filter.dialysis': 'Periton Diyalizi',
    'products.search': '\u00dcr\u00fcn Ara...',
    'products.alpha': 'ABC\u00c7DEFG\u011eHI\u0130JKLMNO\u00d6PRS\u015eTU\u00dcVYZ',
    'products.category': 'Kategori',
    'products.brand': 'Marka',
    'products.view': '\u0130ncele',
    'services.page.title': 'Hizmetlerimiz',
    'services.page.subtitle': 'Kapsaml\u0131 ecza depoculu\u011fu ve da\u011f\u0131t\u0131m \u00e7\u00f6z\u00fcmleri.',
    'branches.title': 'K\u00fcresel Lokasyonlar',
    'branches.subtitle': 'CSC-TR \u0130stanbul Merkez \u2014 CSC-AZ Azerbaycan \u015eubesi. Gelecekte Kazakistan\'da da a\u00e7\u0131lmas\u0131 planlanmaktad\u0131r.',
    'branches.tr.label': 'MERKEZ',
    'branches.tr.name': 'CSC-TR Ecza Deposu',
    'branches.tr.location': '\u0130stanbul, T\u00fcrkiye',
    'branches.az.label': '\u015eUBE',
    'branches.az.name': 'CSC-AZ Ecza Deposu',
    'branches.az.location': 'Bak\u00fc, Azerbaycan',
    'branches.kz.label': 'YAKINDA',
    'branches.kz.name': 'CSC-KZ Ecza Deposu',
    'branches.kz.location': 'Kazakistan (Planlanan)',
    'blog.title': 'Blog',
    'blog.subtitle': 'Orta Asya, Kafkasya ve Afrika\'daki ila\u00e7 pazar\u0131ndaki son geli\u015fmeler, istatistikler ve ithalat d\u00fczenlemeleri.',
    'blog.read': 'Devam\u0131n\u0131 Oku',
    'blog.category.all': 'T\u00fcm\u00fc',
    'blog.close': 'Kapat',
    'blog.category.stats': 'Pazar \u0130statistikleri',
    'blog.category.regulations': 'D\u00fczenlemeler',
    'blog.category.trends': 'Sekt\u00f6r Trendleri',
    'catalog.title': '\u00dcr\u00fcn Katalo\u011fu',
    'catalog.subtitle': 'Kapsaml\u0131 \u00fcr\u00fcn katalo\u011fumuza g\u00f6z at\u0131n. PDF versiyonu yak\u0131nda yay\u0131nda.',
    'catalog.coming': 'Detayl\u0131 \u00fcr\u00fcn katalo\u011fumuz yak\u0131nda indirilebilir olacakt\u0131r. Hemen \u00fcr\u00fcn sorgusu i\u00e7in bize ula\u015f\u0131n.',
    'lang.en': 'EN',
    'lang.tr': 'TR',
    'lang.ru': 'RU',
    'lang.kz': 'KZ',
    'marquee.partners': 'T\u00fcrkiye \u0130la\u00e7 \u00dcreticileri',
    'marquee.label': 'T\u00dcRK\u0130YE \u00dcRET\u0130C\u0130LER\u0130',
    'marquee.title': 'T\u00fcrkiye\'de \u00dcretim Yapan \u0130la\u00e7 Firmalar\u0131',
    'cookie.text': 'Deneyiminizi geli\u015ftirmek i\u00e7in \u00e7erezleri kullan\u0131yoruz. Devam ederek ',
    'cookie.privacy': 'Gizlilik Politikas\u0131',
    'cookie.accept': 'Kabul Et',
    'cookie.reject': 'Reddet',
    'legal.lastupdated': 'Son g\u00fcncelleme',
    'privacy.title': 'Gizlilik Politikas\u0131',
    'terms.title': 'Kullan\u0131m \u015eartlar\u0131',
    'cookiepolicy.title': '\u00c7erez Politikas\u0131',
    'kvkk.title': 'KVKK Ayd\u0131nlatma Metni',
    'about.title': 'Hakk\u0131m\u0131zda',
    'about.values.title': 'De\u011ferlerimiz',
    'about.values.year': 'CSC 2016 senesinden itibaren ila\u00e7lar\u0131n toplam al\u0131m ve sat\u0131m lisans\u0131 ile faaliyet y\u00fcr\u00fctmektedir.',
    'about.values.intro': 'CSC \u00fczerinde t\u00fcm \u00e7al\u0131\u015fmalar\u0131m\u0131z\u0131n y\u00fcr\u00fcd\u00fc\u011f\u00fc \u00fc\u00e7 balinad\u0131r. M\u00dc\u015eTER\u0130LER, \u00c7\u00d6Z\u00dcMLER ve BAKIM.',
    'about.values.gear': 'Bu kavramlar\u0131n iletti\u011fi ve eylemlerimize katt\u0131\u011f\u0131 dev mekanizmadaki ana di\u015fli \u00e7arklar\u0131na benzer.',
    'corporate.tab.about': 'Hakkımızda',
    'corporate.tab.mission': 'Misyon',
    'corporate.tab.vision': 'Vizyon',
    'corporate.tab.branches': 'Şubeler',
    'corporate.tab.certificates': 'Sertifikalar',
    'corporate.tab.team': 'Ekibimiz',
    'corporate.clients.title': 'Müşteriler',
    'corporate.clients.slogan': 'Sözümüzün üstünde dururuz!',
    'corporate.solutions.title': 'Çözümler',
    'corporate.solutions.slogan': 'Çözüm buluruz!',
    'corporate.care.title': 'Önem',
    'corporate.care.slogan': 'Önemsiyoruz!',
    'corporate.clients.desc': 'Sözümüzün üstünde dururuz – iş ve ortakların çıkarlarını kendi çıkarlarımızın üstüne koyar, sorumlu bir şekilde söz veririz\n\nSözümüz, ekibin her bir üyesinin verdiği sözdür.\n\nDürüstüz ve sorunu gizlemeyiz.\n\nYalnızca güvenilir bilgi sunarız.\n\nMüşteri bir doktor, bir eczane, bir ortak, bir üreticidir.',
    'corporate.solutions.desc': 'Çözüm buluruz – girişimciliği, yaratıcılığı ve inovasyonu birleştiririz, problem karşısında girişimde bulunuruz, ilginç ve iddialı hedefler koyarız, kendimizi, işimizi ve süreçlerimizi geliştirmeye çalışırız.\n\nKomuta ile problem çözeriz.\n\nBaşkalarının erdemlerini tanırız. Yeni bir şey yapma girişimlerini teşvik ederiz. Başkalarının hatalarını affederiz, kendimize karşı amansızız.',
    'corporate.care.desc': 'Ürünlerimizin tüketicileri önemsiyoruz – ürünlerimiz konusunda uzman bilgiye sahibiz, hastaların ihtiyaçlarını anlıyoruz.\n\nHastaların sorunlarını daha iyi çözen yeni ürünler arıyor ve bunların ulaşılabilirliğini sağlıyoruz.\n\nDoktorların eğitimini, ürünlerimizin güvenli ve kullanışılı kullanımını önemsiyoruz.\n\nHasta ve doktorlar için hizmetler geliştiriyoruz.',
    'corporate.mission.title': 'Misyonumuz',
    'corporate.mission.body': 'Yüksek kaliteli, Türkiye menşeli ilaçları sağlık kurumlarına dünya genelinde güvenilirlik, hız ve tam düzenleyici uyumlulukla ulaştırmak. Orta Asya, Kafkasya, Afrika ve ötesinde en güvenilir ilaç tedarik ortağı olmayı hedefliyoruz, Türk üreticilerini küresel pazarlarla buluşturuyoruz.',
    'corporate.vision.title': 'Vizyonumuz',
    'corporate.vision.body': 'Türk ilaç üreticilerini küresel pazarlarla birleştiren öncü bir ilaç dağıtım ağı olmak. 2028 yılına kadar dört kıtada tam entegre soğuk zincir ağı, dijital tedarik platformu ve yerel ortaklıklarla 50+ ülkede faaliyet göstermeyi hedefliyoruz.',
    'corporate.team.title': 'Yönetim Ekibimiz',
    'corporate.team.body': 'Ekibimiz deneyimli eczacılar, lojistik uzmanları ve düzenleyici danışmanlardan oluşmaktadır. 10 yılı aşkın ilaç tedarik zinciri deneyimiyle her sevkiyatın en yüksek kalite standartlarını karşılamasını sağlıyoruz.',
    'corporate.title': 'Kurumsal',
    'corporate.subtitle': 'CSC Ecza Deposu hakkında detaylı bilgi edinin.',


  },
  ru: {
    'nav.home': 'Главная',
    'nav.services': 'Услуги',
    'nav.products': 'Продукты',
    'nav.corporate': 'О компании',
    'nav.contact': 'Контакты',
    'nav.about': 'О Нас',
    'nav.blog': 'Блог',
    'nav.catalog': 'Каталог',
    'nav.whatsapp': 'WhatsApp',
    'hero.title': 'Надежные поставки лекарств из Турции в мир',
    'hero.subtitle': 'Мы доставляем лекарственные препараты турецкого происхождения международным фармацевтическим складам с высокими стандартами и быстрой доставкой.',
    'hero.cta': 'Изучить склады',
    'hero.cta2': 'Связаться с нами',
    'hero.scroll': 'Прокрутить вниз',
    'services.label': '',
    'services.title': 'Наши услуги',
    'services.subtitle': 'На каждом этапе фармацевтического склада мы предлагаем услуги, одобренные Министерством здравоохранения и соответствующие GDP.',
    'service.storage.title': 'Услуги хранения',
    'service.storage.desc': 'Мы безопасно храним ваши лекарства на объектах, одобренных Министерством здравоохранения. Холодильная цепь 2-8°C, зоны при комнатной температуре и карантинные участки.',
    'service.storage.chips': 'Хранение 2-8°C,Карантинная зона,Комнатная темп.',
    'service.logistics.title': 'Логистика и дистрибуция',
    'service.logistics.desc': 'Надежная транспортировка лекарств из Турции в мир. Автопарк GDP, системы мониторинга температуры и доставка до двери.',
    'service.logistics.chips': 'Автопарк GDP,До двери,Мониторинг темп.',
    'service.coldchain.title': 'Управление холодильной цепью',
    'service.coldchain.desc': 'Мы доставляем ваши лекарства без нарушения холодильной цепи специальными контейнерами и системами мониторинга в диапазоне 2-8°C.',
    'service.coldchain.chips': 'Контейнеры 2-8°C,Круглосуточный мониторинг,Холод. цепь',
    'service.digital.title': 'Цифровая платформа поставок',
    'service.digital.desc': 'Управляйте всеми процессами в цифровом формате: управление заказами, отслеживание запасов, онлайн-отчетность.',
    'service.digital.chips': 'Управление заказами,Отслеживание,Онлайн-отчеты',
    'service.supply.title': 'Решения цепочки поставок',
    'service.supply.desc': 'Планирование, оптимизация и управление всеми процессами от производителя до конечного потребителя.',
    'service.supply.chips': 'Управление запасами,Срочная доставка,Отслеживание партий',
    'service.bulk.title': 'Услуги оптовых поставок',
    'service.bulk.desc': 'Оптовые заказы для аптек и больниц. Преимущества по стоимости, постоянные поставки и координированное распределение.',
    'service.bulk.chips': 'Оптовые заказы,Стоимость,Коорд. распределение',
    'stats.label': '',
    'stats.title': 'CSC в цифрах',
    'stats.pharmacies': 'Аптек снабжено',
    'stats.pharmacies.detail': 'Аптечная сеть по всему миру',
    'stats.brands': 'Глобальных брендов',
    'stats.brands.detail': 'Проверенные производители',
    'stats.temp': 'Диапазон холод. цепи',
    'stats.temp.detail': 'Круглосуточный мониторинг температуры',
    'stats.experience': 'Лет опыта',
    'stats.experience.detail': 'Одобрено Минздравом',
    'stats.badge': 'Одобрено Минздравом | GDP',
    'stats.badge.sub': 'Good Distribution Practice',
    'coldchain.label': '',
    'coldchain.title': 'Холодная цепь, теплое доверие',
    'coldchain.body': 'Мы никогда не нарушаем холодильную цепь для сохранности ваших лекарств. Специальные изолированные контейнеры при 2-8°C и круглосуточный цифровой мониторинг температуры. GDP-совместимые логистические решения из Турции в мир.',
    'coldchain.feat1': 'Круглосуточный мониторинг температуры',
    'coldchain.feat2': 'GPS отслеживание транспорта',
    'coldchain.feat3': 'GDP-транспортировка',
    'coldchain.live': 'Холодная цепь активна | 4.2°C',
    'products.label': '',
    'products.title': 'Продуктовый портфель',
    'products.subtitle': 'Комплексные фармацевтические и медицинские продукты для учреждений здравоохранения по всему миру.',
    'product.dialysis.title': 'Растворы для перитонеального диализа',
    'product.dialysis.desc': 'Physioneal, Extraneal, Nutrineal и другие. Официальный поставщик растворов от мировых лидеров Baxter и Fresenius.',
    'product.supplies.title': 'Вспомогательные материалы',
    'product.supplies.desc': 'Полный ассортимент наборов, контейнеров, соединительных деталей и других вспомогательных материалов.',
    'product.devices.title': 'Медицинские устройства и оборудование',
    'product.devices.desc': 'Диагностические и лечебные устройства, мониторы, инфузионные насосы и другое медицинское оборудование.',
    'prodcat.title': 'Категории продуктов',
    'prodcat.subtitle': 'Надежные поставки всех групп продуктов, необходимых сектору здравоохранения.',
    'prodcat.ilac.title': 'Фармацевтические продукты',
    'prodcat.ilac.desc': 'Широкий портфель: от антибиотиков до обезболивающих, от сердечно-сосудистых до дерматологических препаратов.',
    'prodcat.ilac.btn': 'Подробнее',
    'prodcat.gida.title': 'Пищевые добавки',
    'prodcat.gida.desc': 'Витамины, минералы, пробиотики, омега-3 и растительные добавки.',
    'prodcat.gida.btn': 'Подробнее',
    'prodcat.sarf.title': 'Медицинские расходные материалы',
    'prodcat.sarf.desc': 'Продукты по уходу за ранами, хирургические расходные материалы, IV-продукты.',
    'prodcat.sarf.btn': 'Подробнее',
    'prodcat.bebek.title': 'Подгузники для взрослых и детей',
    'prodcat.bebek.desc': 'Подгузники для взрослых, впитывающие прокладки, детские подгузники и стомные продукты.',
    'prodcat.bebek.btn': 'Подробнее',
    'prodcat.cihaz.title': 'Медицинские устройства',
    'prodcat.cihaz.desc': 'Неbulизаторы, тонометры, глюкометры и медицинские устройства.',
    'prodcat.cihaz.btn': 'Подробнее',
    'prodcat.test.title': 'Медицинские тесты',
    'prodcat.test.desc': 'Экспресс-тесты, тесты на беременность, полоски для измерения глюкозы и многое другое.',
    'prodcat.test.btn': 'Подробнее',
    'trust.label': '',
    'trust.title': 'Доверие и сертификаты',
    'trust.subtitle': 'Мы осуществляем всю деятельность в соответствии с высочайшими стандартами качества и безопасности.',
    'cert.ministry.title': 'Одобрено Минздравом',
    'cert.ministry.desc': 'Лицензия на фармацевтический склад, одобренная и контролируемая Министерством здравоохранения.',
    'cert.gdp.title': 'Соответствие GDP',
    'cert.gdp.desc': 'Мы управляем всеми процессами в соответствии с Good Distribution Practice.',
    'cert.coldchain.title': 'Сертификация холодильной цепи',
    'cert.coldchain.desc': 'Специальная сертификация и системы мониторинга для хранения и транспортировки при 2-8°C.',
    'cert.quality.title': 'Контроль качества и отслеживание партий',
    'cert.quality.desc': 'Компьютеризированная запись и отслеживание процессов приемки, складирования и отгрузки с помощью штрих-кода.',
    'trust.compliance': 'Срок годности и отслеживание партий всех наших продуктов регистрируется от склада до отгрузки с помощью штрих-кода.',
    'process.label': '',
    'process.title': 'Как это работает?',
    'process.subtitle': 'Надежные фармацевтические поставки в 4 шага через нашу цифровую платформу.',
    'process.step1.title': 'Разместите заказ',
    'process.step1.desc': 'Создайте заказ через нашу веб-платформу или связавшись с нами напрямую.',
    'process.step2.title': 'Утверждение и подготовка',
    'process.step2.desc': 'Ваш заказ утверждается нашим ответственным фармацевтом, проходит контроль качества и готовится.',
    'process.step3.title': 'Логистика и отгрузка',
    'process.step3.desc': 'Мы отправляем лекарства транспортом GDP с системами мониторинга температуры.',
    'process.step4.title': 'Доставка до двери',
    'process.step4.desc': 'Ваши лекарства доставляются по адресу в гигиенических условиях с контролем штрих-кода.',
    'contact.label': '',
    'contact.title': 'Свяжитесь с нами',
    'contact.subtitle': 'Наша команда в офисах с радостью поможет вам.',
    'contact.az.title': 'CSC AZ — Офис в Баку',
    'contact.az.address': 'ГОРОД БАКУ, БИНАГАДИНСКИЙ Р-Н, УЛ. ГЕМЗЕ БАБАШОВА, 9 МКР, ДОМ 1, КВ. 1',
    'contact.tr.title': 'CSC-TR — Офис в Стамбуле',
    'contact.tr.address': 'Kayabasi Mah. Sogutozu Sokak, Basaksehir, Istanbul, Türkiye',
    'contact.email': 'info@csc-tr.com',
    'contact.web': 'csc-tr.com',
    'contact.whatsapp.btn': 'Написать в WhatsApp',
    'contact.emailbtn': 'Отправить email',
    'contact.note': '*Свяжитесь с нами для подробной информации об услугах фармацевтического склада.',
    'contact.form.name': 'Имя',
    'contact.form.surname': 'Фамилия',
    'contact.form.email': 'Email',
    'contact.form.message': 'Сообщение',
    'contact.form.submit': 'Отправить',
    'contact.form.success': 'Ваше сообщение успешно отправлено!',
    'footer.tagline': 'CSC-TR и CSC-AZ — платформа фармацевтического склада и цепочки поставок лекарств, надежно и быстро доставляющая лекарства турецкого происхождения медицинским учреждениям по всему миру.',
    'footer.services': 'Услуги',
    'footer.products': 'Продукты',
    'footer.branches': 'Филиалы',
    'footer.contact': 'Контакты',
    'footer.bottom': '\u00a9 2025 CSC Pharmaceutical Warehouse. Все права защищены.',
    'footer.privacy': 'Политика конфиденциальности',
    'footer.terms': 'Условия использования',
    'footer.gdp': 'GDP',
    'footer.cookie': 'Политика использования cookie',
    'footer.kvkk': 'Заявление о защите данных',
    'modal.title': 'Подтверждение медицинского работника',
    'modal.text': 'Внимание! Этот раздел предназначен исключительно для медицинских работников. Если вы не являетесь медицинским работником, вы можете вернуться на главную страницу.',
    'modal.yes': 'Да, я медицинский работник',
    'modal.no': 'Нет, вернуться на главную',
    'modal.warning': 'Этот раздел содержит информацию о фармацевтических продуктах, предназначенную только для медицинских работников.',
    'products.page.title': 'Фармацевтические продукты',
    'products.page.subtitle': 'Просмотрите наш ассортимент фармацевтических продуктов. Требуется подтверждение медицинского работника.',
    'products.filter.all': 'Все',
    'products.filter.pain': 'Обезболивающие',
    'products.filter.antibiotics': 'Антибиотики',
    'products.filter.coldchain': 'Холодильная цепь',
    'products.filter.dermatology': 'Дерматология',
    'products.filter.cardio': 'Кардиология',
    'products.filter.respiratory': 'Респираторные',
    'products.filter.dialysis': 'Диализ',
    'products.search': 'Поиск продуктов...',
    'products.alpha': 'АБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ',
    'products.category': 'Категория',
    'products.brand': 'Бренд',
    'products.view': 'Подробнее',
    'services.page.title': 'Наши услуги',
    'services.page.subtitle': 'Комплексные решения для фармацевтических складов и дистрибуции.',
    'branches.title': 'Глобальные локации',
    'branches.subtitle': 'CSC-TR Стамбул — CSC-AZ Азербайджан. Планируется расширение в Казахстане.',
    'branches.tr.label': 'ГЛАВНЫЙ ОФИС',
    'branches.tr.name': 'CSC-TR Ecza Deposu',
    'branches.tr.location': 'Стамбул, Турция',
    'branches.az.label': 'ФИЛИАЛ',
    'branches.az.name': 'CSC-AZ Pharmaceutical Warehouse',
    'branches.az.location': 'Баку, Азербайджан',
    'branches.kz.label': 'СКОРО',
    'branches.kz.name': 'CSC-KZ Pharmaceutical Warehouse',
    'branches.kz.location': 'Казахстан (Планируется)',
    'blog.title': 'Блог о фармацевтике',
    'blog.subtitle': 'Последние новости в области фармацевтического экспорта, регулирования импорта и тенденций здравоохранения.',
    'blog.read': 'Читать далее',
    'blog.close': 'Закрыть',
    'blog.category.all': 'Все',
    'blog.category.stats': 'Рыночная статистика',
    'blog.category.regulations': 'Регулирование',
    'blog.category.trends': 'Тенденции отрасли',
    'catalog.title': 'Продуктовый каталог',
    'catalog.subtitle': 'Просмотрите наш продуктовый каталог. PDF-версия скоро будет доступна.',
    'catalog.coming': 'Подробный продуктовый каталог скоро будет доступен для скачивания. Свяжитесь с нами для запроса продуктов.',
    'lang.en': 'EN',
    'lang.tr': 'TR',
    'lang.ru': 'RU',
    'lang.kz': 'KZ',
    'marquee.partners': 'Турецкие фармацевтические производители',
    'marquee.label': 'ТУРЕЦКИЕ ПРОИЗВОДИТЕЛИ',
    'marquee.title': 'Фармацевтические производители Турции',
    'cookie.text': 'Мы используем файлы cookie для улучшения вашего опыта. Продолжая, вы соглашаетесь с нашей ',
    'cookie.privacy': 'Политикой конфиденциальности',
    'cookie.accept': 'Принять',
    'cookie.reject': 'Отклонить',
    'legal.lastupdated': 'Последнее обновление',
    'privacy.title': 'Политика конфиденциальности',
    'terms.title': 'Условия использования',
    'cookiepolicy.title': 'Политика использования cookie',
    'kvkk.title': 'Заявление о защите персональных данных',
    'about.title': 'О Нас',
    'about.values.title': 'Наши ценности',
    'about.values.year': 'CSC работает с лицензией на общую закупку и продажу лекарственных средств с 2016 года.',
    'about.values.intro': 'CSC — это три кита, на которых держится вся наша работа. КЛИЕНТЫ, РЕШЕНИЯ и ЗАБОТА.',
    'about.values.gear': 'Это похоже на главные шестерни в огромном механизме — эти концепции передают и приводят в движение наши действия.',
    'corporate.tab.about': 'О нас',
    'corporate.tab.mission': 'Миссия',
    'corporate.tab.vision': 'Видение',
    'corporate.tab.branches': 'Филиалы',
    'corporate.tab.certificates': 'Сертификаты',
    'corporate.tab.team': 'Команда',
    'corporate.clients.title': 'Клиенты',
    'corporate.clients.slogan': 'Держим слово!',
    'corporate.solutions.title': 'Решения',
    'corporate.solutions.slogan': 'Находим решения!',
    'corporate.care.title': 'Забота',
    'corporate.care.slogan': 'Заботимся!',
    'corporate.clients.desc': 'Мы сдержим своё слово – мы ставим интересы бизнеса и партнёров выше своих собственных, ответственно даём обещания\n\nНаше слово – это слово, данное каждым членом команды.\n\nМы честны и не скрываем проблемы.\n\nМы предоставляем только достоверную информацию.\n\nКлиент – это врач, аптека, партнёр, производитель.',
    'corporate.solutions.desc': 'Мы находим решения – мы сочетаем предпринимательство, креативность и инновации, проявляем инициативу перед лицом проблемы, ставим интересные амбициозные цели, стремимся развивать себя, бизнес и процессы.\n\nМы решаем проблемы командно.\n\nПризнаем заслуги других. Мы поощряем попытки создать новое. Мы прощаем ошибки других, беспощадны к себе.',
    'corporate.care.desc': 'Мы заботимся о потребителях нашей продукции – у нас есть экспертные знания о наших продуктах, мы понимаем потребности пациентов.\n\nМы ищем новые продукты, которые ещё лучше решают проблемы пациентов, и обеспечиваем их доступность.\n\nМы заботимся о обучении врачей, о безопасном и удобном использовании нашей продукции.\n\nМы развиваем услуги для пациентов и врачей.',
    'corporate.mission.title': 'Наша миссия',
    'corporate.mission.body': 'Поставлять высококачественные фармацевтические препараты турецкого происхождения в медицинские учреждения по всему миру с надёжностью, скоростью и полным соблюдением нормативных требований. Мы стремимся стать самым надёжным партнёром по поставкам фармацевтической продукции в Центральной Азии, на Кавказе, в Африке и за их пределами.',
    'corporate.vision.title': 'Наше видение',
    'corporate.vision.body': 'Стать ведущей фармацевтической дистрибуционной сетью, соединяющей турецких производителей лекарственных препаратов с мировыми рынками. К 2028 году мы планируем работать в 50+ странах с полностью интегрированной холодовой цепью, цифровой платформой поставок и местными партнёрствами на четырёх континентах.',
    'corporate.team.title': 'Наша руководящая команда',
    'corporate.team.body': 'Наша команда состоит из опытных фармацевтов, специалистов по логистике и экспертов в области регулирования. Имея более 10 лет опыта в фармацевтической цепочке поставок, мы гарантируем, что каждая поставка соответствует самым высоким стандартам качества.',
    'corporate.title': 'Корпоративный',
    'corporate.subtitle': 'Подробная информация о фармацевтическом складе CSC.',


  },
  kz: {
    'nav.home': 'Басты бет',
    'nav.services': 'Қызметтер',
    'nav.products': 'Өнімдер',
    'nav.corporate': 'Компания туралы',
    'nav.contact': 'Байланыс',
    'nav.about': 'Біз туралы',
    'nav.blog': 'Блог',
    'nav.catalog': 'Каталог',
    'nav.whatsapp': 'WhatsApp',
    'hero.title': 'Түркиядан Әлемге Сенімді Дәрі Қамтамасыз Ету',
    'hero.subtitle': 'Біз түрік тектес дәрілік препараттарды жоғары стандарттармен және тез жеткізу қызметімен халықаралық фармацевтикалық қоймалара жеткіземіз.',
    'hero.cta': 'Қойма Қызметтерін Қарау',
    'hero.cta2': 'Бізбен Байланысу',
    'hero.scroll': 'Төмен Айналдыру',
    'services.label': '',
    'services.title': 'Біздің Қызметтеріміз',
    'services.subtitle': 'Фармацевтикалық қойманың әрбір кезеңінде Денсаулық Сақтау Министрлігі бекіткен және GDP стандарттарына сәйкес қызметтерді ұсынамыз.',
    'service.storage.title': 'Сақтау Қызметтері',
    'service.storage.desc': 'Денсаулық Сақтау Министрлігі бекіткен қоймада дәрілеріңізді қауіпсіз сақтаймыз. 2-8°C суық тізбек, бөлме температурасы аймақтары және карантин бөліктері.',
    'service.storage.chips': '2-8°C Сақтау,Карантин Аймағы,Бөлме Темп.',
    'service.logistics.title': 'Логистика және Тарату',
    'service.logistics.desc': 'Түркиядан әлемге сенімді дәрі тасымалы. GDP стандартты көлік паркі, температура мониторингі және есік-есікке жеткізу.',
    'service.logistics.chips': 'GDP Паркі,Есік-Есікке,Темп. Мониторинг',
    'service.coldchain.title': 'Суық Тізбек Басқаруы',
    'service.coldchain.desc': '2-8°C аралығында арнайы контейнерлер мен мониторинг жүйелері арқылы суық тізбекті бұзбай дәрілеріңізді жеткіземіз.',
    'service.coldchain.chips': '2-8°C Контейнерлер,7/24 Мониторинг,Суық Тізбек',
    'service.digital.title': 'Цифрлық Қамтамасыз Ету Платформасы',
    'service.digital.desc': 'Веб негізінде тапсырыс басқару, қор қадағалау, онлайн есептілік және ақпарат ағымы арқылы барлық үдерістерді цифрлық басқарыңыз.',
    'service.digital.chips': 'Тапсырыс Басқару,Қор Қадағалау,Онлайн Есептер',
    'service.supply.title': 'Қамтамасыз Ету Тізбегі Шешімдері',
    'service.supply.desc': 'Өндірушіден соңғы тұтынушыға дейін барлық үдерістерді жоспарлау, оңтайландыру және басқару. Қор оңтайландыру және шұғыл жөнелту.',
    'service.supply.chips': 'Қор Басқару,Шұғыл Жөнелту,Партия Қадағалау',
    'service.bulk.title': 'Топтық Қамтамасыз Ету Қызметтері',
    'service.bulk.desc': 'Дәріханалар мен ауруханалар үшін топтық тапсырыс мүмкіндігі. Өтімділік артықшылығы, тұрақты қамтамасыз ету және үйлестірілген тарату.',
    'service.bulk.chips': 'Топтық Тапсырыс,Өтімділік Артықш.,ЙAttribs. Тарату',
    'stats.label': '',
    'stats.title': 'CSC Сандық Көрсеткіштерде',
    'stats.pharmacies': 'Дәріхана Қамтамасыз Етілді',
    'stats.pharmacies.detail': 'Бүкіл әлемдегі дәріхана желісі',
    'stats.brands': 'Жаһандық Дәрі Брендтері',
    'stats.brands.detail': 'Әлемдік сенімді өндірушілер',
    'stats.temp': 'Суық Тізбек Аралығы',
    'stats.temp.detail': '7/24 температура мониторингі',
    'stats.experience': 'Жылдық Тәжірибе',
    'stats.experience.detail': 'ДСМ бекіткен операция',
    'stats.badge': 'ДСМ Бекіткен | GDP Сәйкестік',
    'stats.badge.sub': 'Good Distribution Practice',
    'coldchain.label': '',
    'coldchain.title': 'Суық Тізбек, Ыстық Сенім',
    'coldchain.body': 'Дәрілеріңіздің бүтіндігі үшін суық тізбекті ешқашан бұзбаймыз. 2-8°C температура оқшаулауыш контейнерлер мен 7/24 цифрлық температура мониторингі арқылы әр қадам тіркеледі. Түркиядан әлемге GDP стандартты логистикалық шешімдер.',
    'coldchain.feat1': '7/24 Температура Мониторингі',
    'coldchain.feat2': 'GPS Көлік Қадағалауы',
    'coldchain.feat3': 'GDP Сәйкес Тасымал',
    'coldchain.live': 'Суық Тізбек Белсенді | 4.2°C',
    'products.label': '',
    'products.title': 'Өнім Портфелі',
    'products.subtitle': 'Бүкіл әлемдегі денсаулық сақтау мекемелері үшін кешенді фармацевтикалық және медициналық өнімдер.',
    'product.dialysis.title': 'Перитонеальді Диализ Ерітінділері',
    'product.dialysis.desc': 'Physioneal, Extraneal, Nutrineal және басқалары. Baxter, Fresenius сияқты әлемдік көшбасшылардың ресми жеткізушісі.',
    'product.supplies.title': 'Қосалқы Материалдар',
    'product.supplies.desc': 'Перитонеальді диализ емінде қолданылатын жиынтықтар, контейнерлер, қосу бөлшектері және басқа қосалқы материалдар.',
    'product.devices.title': 'Медициналық Құрылғылар және Жабдық',
    'product.devices.desc': 'Диагностикалық және емдік құрылғылар, мониторлар, инфузиялық сорғылар және денсаулық сақтау саласына арналған басқа медициналық жабдық.',
    'prodcat.title': 'Өнім Санаттары',
    'prodcat.subtitle': 'Денсаулық сақтау саласына қажетті барлық өнім топтарында сенімді қамтамасыз ету.',
    'prodcat.ilac.title': 'Дәрілік Өнімдер',
    'prodcat.ilac.desc': 'Антибиотиктерден ауыру басқышқа, жүрек-тамыр дәрілерінен дерматологиялық өнімдерге кең портфель.',
    'prodcat.ilac.btn': 'Қарау',
    'prodcat.gida.title': 'Тамақтық Қоспалар',
    'prodcat.gida.desc': 'Витаминдер, минералдар, пробиотиктер, омега-3 және өсімдік қоспалары.',
    'prodcat.gida.btn': 'Қарау',
    'prodcat.sarf.title': 'Медициналық Жабдықтар',
    'prodcat.sarf.desc': 'Жара қамқорлығы өнімдері, хирургиялық жабдықтар, IV өнімдері және диагностикалық материалдар.',
    'prodcat.sarf.btn': 'Қарау',
    'prodcat.bebek.title': 'Науқас және Бала Жапқыштары',
    'prodcat.bebek.desc': 'Ересек науқас жапқыштары, сіңіргіш төсемдер, бала жапқыштары және стома өнімдері.',
    'prodcat.bebek.btn': 'Қарау',
    'prodcat.cihaz.title': 'Медициналық Құрылғылар',
    'prodcat.cihaz.desc': 'Не bulизаторлар, қан қысымы аппараттары, глюкометрлер және медициналық құрылғылар.',
    'prodcat.cihaz.btn': 'Қарау',
    'prodcat.test.title': 'Медициналық Тесттер',
    'prodcat.test.desc': 'Жедел диагностикалық тесттер, жүктілік тесттері, қан қантын өлшеу таспалары және т.б.',
    'prodcat.test.btn': 'Қарау',
    'trust.label': '',
    'trust.title': 'Сенім және Сертификаттар',
    'trust.subtitle': 'Барлық қызметтерімізді ең жоғары сапа және қауіпсіздік стандарттарына, заңнама талаптарына толық сәйкес жүзеге асырамыз.',
    'cert.ministry.title': 'ДСМ Бекіткен',
    'cert.ministry.desc': 'Денсаулық Сақтау Министрлігі бекіткен және қадағалаған дәріхана қоймасы лицензиясы.',
    'cert.gdp.title': 'GDP Сәйкестік',
    'cert.gdp.desc': 'Good Distribution Practice шеңберінде барлық үдерістерді басқарамыз.',
    'cert.coldchain.title': 'Суық Тізбек Сертификаттауы',
    'cert.coldchain.desc': '2-8°C аралығында сақтау және тасымалдау үшін арнайы сертификаттау және мониторинг жүйелері.',
    'cert.quality.title': 'Сапа Бақылауы және Партия Қадағалауы',
    'cert.quality.desc': 'Штрих-код жүйесі арқылы өнімді қабылдау, қор және жөнелту үдерістерінің компьютерлік тіркеуі және қадағалануы.',
    'trust.compliance': 'Барлық өнімдеріміздің мерзімі және партия қадағалауы штрих-код жүйесі арқылы қордан жөнелтуге дейін тіркеледі. ДСМ тәртіптемелеріне сәйкес суық тізбек, гигиена және қауіпсіздік стандарттарын ең жоғары деңгейде қолданамыз.',
    'process.label': '',
    'process.title': 'Қалай Жұмыс Істейді?',
    'process.subtitle': 'Цифрлық платформа арқылы 4 қадамда сенімді дәрі қамтамасыз ету.',
    'process.step1.title': 'Тапсырыс Беріңіз',
    'process.step1.desc': 'Веб-платформа арқылы немесе тікелей хабарласып тапсырысыңызды жасаңыз.',
    'process.step2.title': 'Бекіту және Дайындау',
    'process.step2.desc': 'Тапсырысыңыз жауапты фармацевт мүддесіміз бекітеді, сапа бақылауынан өтеді және дайындалады.',
    'process.step3.title': 'Логистика және Жөнелту',
    'process.step3.desc': 'GDP стандартты көліктермен, температура мониторингімен дәрілерді жолға салады.',
    'process.step4.title': 'Есігіңізге Жеткізу',
    'process.step4.desc': 'Дәрілеріңіз гигиеналық жағдайларда, штрих-код бақылауымен мекенжайыңызға жеткізіледі.',
    'contact.label': '',
    'contact.title': 'Бізбен Байланысыңыз',
    'contact.subtitle': 'Әзірбайжан және Түркиядағы кеңселерімізден командамыз көмектесуге қуанышты.',
    'contact.az.title': 'CSC AZ — Баку Кеңсесі',
    'contact.az.address': 'БАКУ ҚАЛАСЫ, БІНАГАДІ АУДАНЫ, ҒӘМЗӘ БАБАШОВ КӨШЕСІ, 9 МШР, ҮЙ 1, ПӘТЕР 1',
    'contact.tr.title': 'CSC-TR — Ыстанбұл Кеңсесі',
    'contact.tr.address': 'Kayabasi Mah. Sogutozu Sokak, Basaksehir, Istanbul, Türkiye',
    'contact.email': 'info@csc-tr.com',
    'contact.web': 'csc-tr.com',
    'contact.whatsapp.btn': 'WhatsApp-А Жазу',
    'contact.emailbtn': 'Email Жіберу',
    'contact.note': '*Фармацевтикалық қойма қызметтеріміз туралы толық ақпарат алу үшін бізбен байланысыңыз.',
    'contact.form.name': 'Аты',
    'contact.form.surname': 'Тегі',
    'contact.form.email': 'Email',
    'contact.form.message': 'Хабарлама',
    'contact.form.submit': 'Жіберу',
    'contact.form.success': 'Хабарламаңыз сәтті жіберілді!',
    'footer.tagline': 'CSC-TR және CSC-AZ — түрік тектес дәрілік препараттарды әлемдегі денсаулық сақтау мекемелеріне сенімді және тез жеткізетін фармацевтикалық қойма және дәрі қамтамасыз ету тізбегі платформасы.',
    'footer.services': 'Қызметтер',
    'footer.products': 'Өнімдер',
    'footer.branches': 'Филиалдар',
    'footer.contact': 'Байланыс',
    'footer.bottom': '\u00a9 2025 CSC Pharmaceutical Warehouse. Барлық құқықтар қорғалған.',
    'footer.privacy': 'Құпиялылық Саясаты',
    'footer.terms': 'Пайдалану Шарттары',
    'footer.gdp': 'GDP',
    'footer.cookie': 'Cookie Саясаты',
    'footer.kvkk': 'Жеке Деректерді Қорғау',
    'modal.title': 'Медицина Қызметкері Растауы',
    'modal.text': 'Назар аударыңыз! Бұл бөлім тек медицина қызметкерлері үшін жасалған. Егер сіз медицина қызметкері болмасаңыз, басты бетке орала аласыз.',
    'modal.yes': 'Иә, мен медицина қызметкерімін',
    'modal.no': 'Жоқ, басты бетке оралу',
    'modal.warning': 'Бұл бөлім тек медицина қызметкерлеріне арналған дәрі туралы ақпаратты қамтиды.',
    'products.page.title': 'Дәрілік Өнімдер',
    'products.page.subtitle': 'Дәрілік өнімдеріміздің кең ауқымын шолыңыз. Медицина қызметкерін растау қажет.',
    'products.filter.all': 'Барлығы',
    'products.filter.pain': 'Ауыру Басқыштар',
    'products.filter.antibiotics': 'Антибиотиктер',
    'products.filter.coldchain': 'Суық Тізбек',
    'products.filter.dermatology': 'Дерматология',
    'products.filter.cardio': 'Кардиология',
    'products.filter.respiratory': 'Тыныс Алу Жүйесі',
    'products.filter.dialysis': 'Диализ',
    'products.search': 'Өнімді Іздеу...',
    'products.alpha': 'АБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ',
    'products.category': 'Санат',
    'products.brand': 'Бренд',
    'products.view': 'Қарау',
    'services.page.title': 'Біздің Қызметтеріміз',
    'services.page.subtitle': 'Кешенді фармацевтикалық қойма және тарату шешімдері.',
    'branches.title': 'Жаһандық Орналасулар',
    'branches.subtitle': 'CSC-TR Ыстанбул — CSC-AZ Әзірбайжан. Қазақстанда кеңею жоспарлануда.',
    'branches.tr.label': 'БАСТЫ КЕҢСЕ',
    'branches.tr.name': 'CSC-TR Ecza Deposu',
    'branches.tr.location': 'Ыстанбұл, Түркия',
    'branches.az.label': 'ФИЛИАЛ',
    'branches.az.name': 'CSC-AZ Pharmaceutical Warehouse',
    'branches.az.location': 'Баку, Әзірбайжан',
    'branches.kz.label': 'ЖАҚЫНДА',
    'branches.kz.name': 'CSC-KZ Pharmaceutical Warehouse',
    'branches.kz.location': 'Қазақстан (Жоспарлануда)',
    'blog.title': 'Фарма Блогы',
    'blog.subtitle': 'Орта Азия, Кавказ және Африкадағы фармацевтикалық экспорт, импорт ережелері және денсаулық сақтау тенденциялары туралы соңғы жаңалықтар.',
    'blog.read': 'Толығырақ Оқу',
    'blog.close': 'Жабу',
    'blog.category.all': 'Барлығы',
    'blog.category.stats': 'Нарық Статистикасы',
    'blog.category.regulations': 'Ережелер',
    'blog.category.trends': 'Салалық Тенденциялар',
    'catalog.title': 'Өнім Каталогы',
    'catalog.subtitle': 'Біздің кешенді өнім каталогын шолыңыз. PDF нұсқасы жақында қолжетімді болады.',
    'catalog.coming': 'Толық өнім каталогымыз жақында жүктеп алуға қолжетімді болады. Өнім сұранысы үшін бізбен байланысыңыз.',
    'lang.en': 'EN',
    'lang.tr': 'TR',
    'lang.ru': 'RU',
    'lang.kz': 'KZ',
    'marquee.partners': 'Түрік фармацевтикалық өндірушілері',
    'marquee.label': 'ТҮРІК ӨНДІРУШІЛЕРІ',
    'marquee.title': 'Түркияда өндіріс жүргізетін дәрі өндірушілер',
    'cookie.text': 'Тәжірибеңізді жақсарту үшін cookie файлдарын қолданамыз. Жалғастыра отырып, біздің ',
    'cookie.privacy': 'Құпиялылық Саясатымызбен',
    'cookie.accept': 'Қабылдау',
    'cookie.reject': 'Бас тарту',
    'legal.lastupdated': 'Соңғы жаңарту',
    'privacy.title': 'Құпиялылық Саясаты',
    'terms.title': 'Пайдалану Шарттары',
    'cookiepolicy.title': 'Cookie Саясаты',
    'kvkk.title': 'Жеке Деректерді Қорғау Хабарламасы',
    'about.title': 'Біз туралы',
    'about.values.title': 'Біздің құндылықтарымыз',
    'about.values.year': 'CSC 2016 жылдан бастап дәрі-дәрмекті сатып алу және сатуға арналған толық лицензиямен жұмыс істейді.',
    'about.values.intro': 'CSC — біздің барлық жұмысымыздың сүйенгені үшутін. ТАПСЫРЫШТАР, ШЕШІМДЕР және ҚАМҚОРЛЫҚ.',
    'about.values.gear': 'Бұл ұғымдар жеткізетін және әрекеттерімізге әкелетін алып механизмдегі негізгі тіректерге ұқсас.',
    'corporate.tab.about': 'Біз туралы',
    'corporate.tab.mission': 'Миссия',
    'corporate.tab.vision': 'Көрініс',
    'corporate.tab.branches': 'Филиалдар',
    'corporate.tab.certificates': 'Сертификаттар',
    'corporate.tab.team': 'Команда',
    'corporate.clients.title': 'Тапсырышылар',
    'corporate.clients.slogan': 'Сөзіміздің үстінде тұрамыз!',
    'corporate.solutions.title': 'Шешімдер',
    'corporate.solutions.slogan': 'Шешім табамыз!',
    'corporate.care.title': 'Қамқорлық',
    'corporate.care.slogan': 'Қамқорлық көрсетеміз!',
    'corporate.clients.desc': 'Біз өз сөзіміздің үстінде тұрамыз – бізнес және сәріктестердің мүддесін өз мүддесімізден үстіне қоямзыларымыз, жауапкершілік үшін сөз береміз\n\nҰшіміздің сөзіміз – бул команда мүшесінің берген сөзі.\n\nБіз шынаймыз және мәселені жасырмаймыз.\n\nТек қол қадағы ақпарат себетерім қамтамасыз етеміз.\n\nТапсырышты – бул дәрігер, дері хана, сәріктес, өндіруші.',
    'corporate.solutions.desc': 'Біз шешім табамыз – қарменділіктілікті, шынаймшылықты және жаңалы екен адамыз, мәселенің бетінде бас инициатива көрсетеміз, қызықты және мақсат мақсаттар қойямыз, өзімізді, бизнесімізді және процестерді дамиту қарайттық қарайдымыз.\n\nБыз команда арқылы мәселелерді шешеміз.\n\nБасқалардың жақсырттарын танымыз. Быз жаңа бір нәрсені құру тыыстарын қолдаймыз. Басқалардың қателерін кешіреміз, өзімізге қатты боламыз.',
    'corporate.care.desc': 'Біз өзіміздің тұтынушылары қамқорлаймыз – өз өзіміздің эксперт біліміз бар, науқастардың қажеттерін тұсинаймыз.\n\nНауқастардың мәселелерін өзі шешетін жаңа өүптер іздейміз, олардың қол жетімділігін қамтамасыз етеміз.\n\nДәрігердің тәрбиелесіне, өз өзіміздің қауіпсіз және өнемді қолдануын қамқорлаймыз.\n\nБіз науқастар қалды және дәрігерлер үшін қызметтер қамтамасыз етеміз.',
    'corporate.mission.title': 'Біздің миссиямыз',
    'corporate.mission.body': 'Жоғары сапалы, Түркия текті дәрілік препараттарды денсаулық сақтау мекемелеріне бүкіл әлем бойынша сенімділік, жылдамдық және толық нормативтік сәйкестікпен жеткізу. Орта Азия, Кавказ, Африка және одан әрі аймақтардағы ең сенімді фармацевтикалық қамтамасыз ету серіктесі болуды мақсат тұтамыз.',
    'corporate.vision.title': 'Біздің көрінісіміз',
    'corporate.vision.body': 'Түрік фармацевтикалық өндірушілерін жаһандық нарықтармен байланыстыратын алдыңғы қатарлы фармацевтикалық тарату желісі болу. 2028 жылға қарай төрт құрлықта толық интеграцияланған суық тізбек, сандық жабдықтау платформасы және жергілікті серіктестіктермен 50+ елде жұмыс істеуді мақсат тұтамыз.',
    'corporate.team.title': 'Біздің басқару командамыз',
    'corporate.team.body': 'Біздің командамыз тәжірибелі фармацевттер, логистика мамандары және реттеу сарапшыларынан тұрады. Фармацевтикалық тізбек бойынша 10 жылдан астам тәжірибемізбен біз әрбір жөнелтудің ең жоғары сапа стандарттарына сай екеніне кепілдік береміз.',
    'corporate.title': 'Корпоративтік',
    'corporate.subtitle': 'CSC дәріхана қоймасы туралы толық ақпарат алыңыз.',


  },
  az: {
    'nav.home': 'Ana səhifə',
    'nav.services': 'Xidmətlər',
    'nav.products': 'Məhsullar',
    'nav.corporate': 'Korporativ',
    'nav.contact': 'Əlaqə',
    'nav.about': 'Haqqımızda',
    'nav.blog': 'Blog',
    'nav.catalog': 'Kataloq',
    'nav.whatsapp': 'WhatsApp',
    'hero.title': 'Türkiyədən Dünyaya Etibarlı Dərman Təchizatı',
    'hero.subtitle': 'Türkiyə mənşəli dərmanları yüksək standartlarda və sürətli çatdırılma xidmətilə beynəlxalq anbarlara çatdırırıq.',
    'hero.cta': 'Anbar Xidmətlərini Kəşf Edin',
    'hero.cta2': 'Bizimlə Əlaqə',
    'hero.scroll': 'Aşağı Sürüşdürün',
    'services.label': '',
    'services.title': 'Xidmətlərimiz',
    'services.subtitle': 'Hər mərhələdə Səhiyyə Nazirliyi tərəfindən təsdiqlənmiş və GDP uyğun xidmətlər təqdim edirik.',
    'service.storage.title': 'Saxlama Xidmətləri',
    'service.storage.desc': 'Səhiyyə Nazirliyi tərəfindən təsdiqlənmiş anbarlarımızda dərmanlarınızı etibarlı şəkildə saxlayırıq. 2-8°C soyuducu zəncir saxlama, otaq temperaturu zonaları və karantin bölmələri.',
    'service.storage.chips': '2-8°C Saxlama,Karantin Zonası,Otaq Temperaturu',
    'service.logistics.title': 'Logistika və Dağıtım',
    'service.logistics.desc': 'Türkiyədən dünyaya etibarlı dərman daşınması. GDP uyğun avtomobil parkı, temperatur izləmə sistemləri və qapıdan-qapıya çatdırılma.',
    'service.logistics.chips': 'GDP Parkı,Qapıdan Qapıya,Temperatur İzləmə',
    'service.coldchain.title': 'Soyuducu Zəncir İdarəetməsi',
    'service.coldchain.desc': '2-8°C temperatur aralığında xüsusi konteynerlər və izləmə sistemləri ilə soyuducu zənciri qırmadan dərmanlarınızı çatdırırıq.',
    'service.coldchain.chips': '2-8°C Konteyner,7/24 İzləmə,Soyuducu Zəncir',
    'service.digital.title': 'Rəqəmsal Təchizat Platforması',
    'service.digital.desc': 'Veb əsaslı sifariş idarəetməsi, ehtiyat izləməsi, onlayn hesabatlar və məlumat axını ilə bütün prosesləri rəqəmsal idarə edin.',
    'service.digital.chips': 'Sifariş İdarəetməsi,Ehtiyat İzləmə,Onlayn Hesabatlar',
    'service.supply.title': 'Təchizat Zənciri Həlləri',
    'service.supply.desc': 'İstehsalçıdan son istehlakçıya qədər bütün proseslərin planlaşdırılması, optimallaşdırılması və idarə edilməsi.',
    'service.supply.chips': 'Ehtiyat İdarəetməsi,Təcili Göndərmə,Lot İzləmə',
    'service.bulk.title': 'Toplu Təchizat Xidmətləri',
    'service.bulk.desc': 'Apteklər və xəstəxanalar üçün toplu sifariş imkanı. Xərclər üstünlüyü, ardıcıl təchizat və koordinasiyalı paylanma.',
    'service.bulk.chips': 'Toplu Sifariş,Xərc Üstünlüyü,Koordinasiyalı Paylanma',
    'stats.label': '',
    'stats.title': 'Rəqəmlərlə CSC',
    'stats.pharmacies': 'Aptekə Təchizat',
    'stats.pharmacies.detail': 'Dünya üzrə aptek şəbəkəsi',
    'stats.brands': 'Qlobal Dərman Markası',
    'stats.brands.detail': 'Etibarlı istehsalçılar',
    'stats.temp': 'Soyuducu Zəncir Aralığı',
    'stats.temp.detail': '7/24 temperatur izləmə və qeyd',
    'stats.experience': 'İllik Sənaye Təcrübəsi',
    'stats.experience.detail': 'Səhiyyə Nazirliyi təsdiqli əməliyyat',
    'stats.badge': 'Səhiyyə Nazirliyi Təsdiqli | GDP Uyğun',
    'stats.badge.sub': 'Good Distribution Practice',
    'coldchain.label': '',
    'coldchain.title': 'Soyuducu Zəncir, İsti Etibar',
    'coldchain.body': 'Dərmanlarınızın sağlamlığı üçün soyuducu zənciri heç vaxt qırmırıq. 2-8°C temperatur izolyasiyalı konteynerlər və 7/24 rəqəmsal temperatur izləmə ilə hər addım qeydə alınır. Türkiyədən dünyaya GDP uyğun logistika həlləri.',
    'coldchain.feat1': '7/24 Temperatur İzləmə',
    'coldchain.feat2': 'GPS Nəqliyyat İzləməsi',
    'coldchain.feat3': 'GDP Uyğun Daşınma',
    'coldchain.live': 'Soyuducu Zəncir Aktiv | 4.2°C',
    'products.label': '',
    'products.title': 'Məhsul Portfeli',
    'products.subtitle': 'Dünya üzrə səhiyyə müəssisələri üçün hərtərəfli dərman və tibbi məhsullar.',
    'product.dialysis.title': 'Peritoneal Dializ Məhlulları',
    'product.dialysis.desc': 'Physioneal, Extraneal, Nutrineal və digərləri. Baxter, Fresenius kimi dünya liderlərinin rəsmi təchizatçısı.',
    'product.supplies.title': 'Köməkçi Materiallar',
    'product.supplies.desc': 'Peritoneal dializ müalicəsində istifadə edilən dəstlər, konteynerlər, bağlantı hissələri və digər köməkçi materiallar.',
    'product.devices.title': 'Tibbi Avadanlıqlar və Qurğular',
    'product.devices.desc': 'Diaqnostik və müalicə avadanlıqları, monitore, infüziya nasosları və digər tibbi avadanlıqlar.',
    'prodcat.title': 'Məhsul Kateqoriyaları',
    'prodcat.subtitle': 'Səhiyyə sektorunun ehtiyac duyduğu bütün məhsul qruplarında etibarlı təchizat.',
    'prodcat.ilac.title': 'Dərman Məhsulları',
    'prodcat.ilac.desc': 'Antibiotiklərdən ağrıkəsənlərə, ürək-damar dərmanlarından dərmatoloji məhsullara geniş portfel.',
    'prodcat.ilac.btn': 'Kəşf Et',
    'prodcat.gida.title': 'Qida Əlavələri',
    'prodcat.gida.desc': 'Vitaminlər, minerallar, probiotiklər, omega-3 və bitki əlavələri.',
    'prodcat.gida.btn': 'Kəşf Et',
    'prodcat.sarf.title': 'Tibbi Sarf Materialları',
    'prodcat.sarf.desc': 'Yara qayğı məhsulları, cərrahi sarf materialları, IV məhsulları və diaqnostik materiallar.',
    'prodcat.sarf.btn': 'Kəşf Et',
    'prodcat.bebek.title': 'Xəstə və Körpə Bezləri',
    'prodcat.bebek.desc': 'Böyük xəstə bezləri, udsoran pedyurlar, körpə bezləri və stoma məhsulları.',
    'prodcat.bebek.btn': 'Kəşf Et',
    'prodcat.cihaz.title': 'Tibbi Qurğular',
    'prodcat.cihaz.desc': 'Nebulizatorlar, qan təzyiqi aparatları, qlükometrlər və tibbi qurğular.',
    'prodcat.cihaz.btn': 'Kəşf Et',
    'prodcat.test.title': 'Tibbi Testlər',
    'prodcat.test.desc': 'Sürətli diaqnostik testlər, hamiləlik testləri, qan şəkəri zolaqları və digərləri.',
    'prodcat.test.btn': 'Kəşf Et',
    'trust.label': '',
    'trust.title': 'Etibar və Sertifikatlar',
    'trust.subtitle': 'Bütün fəaliyyətimizi ən yüksək keyfiyyət və təhlükəsizlik standartlarında, qanunvericiliyə tam uyğun həyata keçiririk.',
    'cert.ministry.title': 'Səhiyyə Nazirliyi Təsdiqli',
    'cert.ministry.desc': 'Səhiyyə Nazirliyi tərəfindən təsdiqlənmiş və nəzarət olunan dərman anbarı lisenziyası.',
    'cert.gdp.title': 'GDP Uyğunluq',
    'cert.gdp.desc': 'Good Distribution Practice çərçivəsində bütün prosesləri idarə edirik.',
    'cert.coldchain.title': 'Soyuducu Zəncir Sertifikasiyası',
    'cert.coldchain.desc': '2-8°C temperatur aralığında saxlama və daşınma üçün xüsusi sertifikasiya və izləmə sistemləri.',
    'cert.quality.title': 'Keyfiyyət Nəzarəti və Lot İzləmə',
    'cert.quality.desc': 'Ştrix-kod sistemi ilə məhsul qəbulu, ehtiyat və göndərmə proseslərinin kompüterdə qeydi və izlənməsi.',
    'trust.compliance': 'Bütün məhsullarımızın son istifadə tarixi və lot izlənməsi ştrix-kod sistemi ilə anbardan göndərməyə qədər qeydə alınır. Səhiyyə Nazirliyi prosedurlərinə uyğun olaraq soyuducu zəncir, gigiyena və təhlükəsizlik standartlarını ən yüksək səviyyədə tətbiq edirik.',
    'process.label': '',
    'process.title': 'Necə İşləyir?',
    'process.subtitle': 'Rəqəmsal platformamız üzərindən 4 addımda etibarlı dərman təchizatı.',
    'process.step1.title': 'Sifariş Verin',
    'process.step1.desc': 'Veb platformamız üzərindən və ya birbaşa əlaqə saxlayaraq sifarişinizi yaradın.',
    'process.step2.title': 'Təsdiq və Hazırlıq',
    'process.step2.desc': 'Sifarişiniz cavabdeh aptekarımız tərəfindən təsdiqlənir, keyfiyyət yoxlanılır və hazırlanır.',
    'process.step3.title': 'Logistika və Göndərmə',
    'process.step3.desc': 'GDP uyğun avtomobillərlə, temperatur izləmə sistemləri ilə dərmanları yola salırıq.',
    'process.step4.title': 'Qapınıza Çatdırılma',
    'process.step4.desc': 'Dərmanlarınız gigiyena şəraitində, ştrix-kod nəzarəti ilə ünvanınıza çatdırılır.',
    'contact.label': '',
    'contact.title': 'Bizimlə Əlaqə',
    'contact.subtitle': 'Azərbaycan və Türkiyə ofislərimizdən komandamız köməklik göstərməkdən məmnunluq duyacaq.',
    'contact.az.title': 'CSC AZ — Bakı Ofisi',
    'contact.az.address': 'BAKI ŞƏHƏRİ, BİNƏQƏDİ RAYONU, HƏMZƏ BABAŞOV KÜÇƏSİ, 9 MKR, EV 1, DƏNGƏ 1',
    'contact.tr.title': 'CSC-TR — İstanbul Ofisi',
    'contact.tr.address': 'Kayabaşı Mah. Söğütözü Sokak, Başakşehir, İstanbul',
    'contact.email': 'info@csc-tr.com',
    'contact.web': 'csc-tr.com',
    'contact.whatsapp.btn': 'WhatsApp-da Yazın',
    'contact.emailbtn': 'E-poçt Göndərin',
    'contact.note': '*Dərman anbarı xidmətlərimiz haqqında ətraflı məlumat üçün bizimlə əlaqə saxlayın.',
    'contact.form.name': 'Ad',
    'contact.form.surname': 'Soyad',
    'contact.form.email': 'E-poçt',
    'contact.form.message': 'Mesaj',
    'contact.form.submit': 'Göndər',
    'contact.form.success': 'Mesajınız uğurla göndərildi!',
    'footer.tagline': 'CSC-TR və CSC-AZ, Türkiyə mənşəli dərmanları dünyadakı səhiyyə müəssisələrinə etibarlı və sürətli şəkildə çatdıran dərman anbarı və dərman təchizat zənciri platforması.',
    'footer.services': 'Xidmətlər',
    'footer.products': 'Məhsullar',
    'footer.branches': 'Filiallar',
    'footer.contact': 'Əlaqə',
    'footer.bottom': '© 2025 CSC Dərman Anbarı. Bütün hüquqlar qorunur.',
    'footer.privacy': 'Məxfilik Siyasəti',
    'footer.terms': 'İstifadə Şərtləri',
    'footer.gdp': 'GDP Uyğunluq',
    'footer.cookie': 'Cookie Siyasəti',
    'footer.kvkk': 'Şəxsi Məlumatların Qorunması',
    'modal.title': 'Səhiyyə İşçisi Təsdiqi',
    'modal.text': 'Diqqət! Bu bölmə yalnız səhiyyə işçiləri üçün nəzərdə tutulub. Səhiyyə işçisi deyilsinizsə, ana səhifəyə qayıda bilərsiniz.',
    'modal.yes': 'Bəli, səhiyyə işçisiyəm',
    'modal.no': 'Xeyr, ana səhifəyə qayıt',
    'modal.warning': 'Bu bölmə yalnız səhiyyə işçilərinə yönəlik dərman məlumatlarını ehtiva edir.',
    'products.page.title': 'Dərman Məhsulları',
    'products.page.subtitle': 'Dərman məhsullarımızın geniş çeşidini nəzərdən keçirin. Səhiyyə işçisi təsdiqi tələb olunur.',
    'products.filter.all': 'Hamısı',
    'products.filter.pain': 'Ağrıkəsənlər',
    'products.filter.antibiotics': 'Antibiotiklər',
    'products.filter.coldchain': 'Soyuducu Zəncir',
    'products.filter.dermatology': 'Dermatologiya',
    'products.filter.cardio': 'Ürək-Damar',
    'products.filter.respiratory': 'Tənəffüs Sistemi',
    'products.filter.dialysis': 'Dializ',
    'products.search': 'Məhsul Axtar...',
    'products.alpha': 'ABCÇDEFGĞHIİJKLMNOÖPRSŞTUÜVYZ',
    'products.category': 'Kateqoriya',
    'products.brand': 'Marka',
    'products.view': 'Bax',
    'services.page.title': 'Xidmətlərimiz',
    'services.page.subtitle': 'Hərtərəfli dərman anbarı və paylanma həlləri.',
    'branches.title': 'Qlobal Lokasiyalar',
    'branches.subtitle': 'CSC-TR İstanbul Mərkəz — CSC-AZ Azərbaycan Filialı. Gələcəkdə Qazaxıstanda da genişlənmə planlaşdırılır.',
    'branches.tr.label': 'MƏRKƏZ',
    'branches.tr.name': 'CSC-TR Dərman Anbarı',
    'branches.tr.location': 'İstanbul, Türkiyə',
    'branches.az.label': 'FİLİAL',
    'branches.az.name': 'CSC-AZ Dərman Anbarı',
    'branches.az.location': 'Bakı, Azərbaycan',
    'branches.kz.label': 'TEZLİKDƏ',
    'branches.kz.name': 'CSC-KZ Dərman Anbarı',
    'branches.kz.location': 'Qazaxıstan (Planlaşdırılır)',
    'blog.title': 'Farm Insights Blogu',
    'blog.subtitle': 'Mərkəzi Asiya, Qafqaz və Afrikada dərman ixracı, idxal qaydaları və səhiyyə trendləri.',
    'blog.read': 'Daha Çox Oxu',
    'blog.close': 'Bağla',
    'blog.category.all': 'Hamısı',
    'blog.category.stats': 'Bazar Statistikası',
    'blog.category.regulations': 'Qaydalar',
    'blog.category.trends': 'Sənaye Trendləri',
    'catalog.title': 'Məhsul Kataloqu',
    'catalog.subtitle': 'Hərtərəfli məhsul kataloqumuza nəzər salın. PDF versiyası tezliklə əlçatan olacaq.',
    'catalog.coming': 'Ətraflı məhsul kataloqumuz tezliklə yüklənə bilən olacaq. Məhsul sorğusu üçün bizimlə əlaqə saxlayın.',
    'lang.en': 'EN',
    'lang.tr': 'TR',
    'lang.ru': 'RU',
    'lang.kz': 'KZ',
    'lang.az': 'AZ',
    'marquee.partners': 'Qlobal Dərman Tərəfdaşları',
    'marquee.label': 'TÜRK İSTEHSALÇILARI',
    'marquee.title': 'Türkiyədə İstehsal Edən Dərman Şirkətləri',
    'cookie.text': 'Təcrübənizi yaxşılaşdırmaq üçün cookie fayllarından istifadə edirik. Davam edərək, bizim ',
    'cookie.privacy': 'Məxfilik Siyasətimizlə',
    'cookie.accept': 'Qəbul Et',
    'cookie.reject': 'Rədd Et',
    'legal.lastupdated': 'Son yeniləmə',
    'privacy.title': 'Məxfilik Siyasəti',
    'terms.title': 'İstifadə Şərtləri',
    'cookiepolicy.title': 'Cookie Siyasəti',
    'kvkk.title': 'Şəxsi Məlumatların Qorunması Bəyanatı',
    'about.title': 'Haqqımızda',
    'about.subtitle': 'CSC Global Ecza Deposu — Türkiyə mənşəli dərmanların dünyaya etibarlı ünvanı.',
    'about.mission.title': 'Missiyamız',
    'about.mission.desc': 'Milyonlarla xəstə üçün yüksək keyfiyyətli, innovativ terapiya variantlarına çatmaq imkanı yaratmaq. Məqsədimiz Türkiyədə istehsal olunan ən etibarlı dərman məhsullarını dünya bazarlarına çatdırmaq, səhiyyə müəssisələrinə güvənli və sürətli təchizat təmin etməkdir.',
    'about.history.title': 'Tariximiz',
    'about.history.desc': 'CSC Ecza Deposu, illərdir dərman sektorunda fəaliyyət göstərən, Türkiyədə istehsal olunan dərmanların ixracında lider mövqe tutan bir platformadır. Türkiyə-Rusiya və Türkiyə-Qafqaz dəhlizi üzərində qurduğumuz logistika şəbəkəsi ilə milyonlarla xəstəyə çatdırdıq. Sağlamlıq Nazirliyinin təsdiqi və GDP uyğunluğu ilə bütün əməliyyatlarımızı beynəlxalq standartlarda həyata keçiririk.',
    'about.values.title': 'Dəyərlərimiz',
    'about.values.year': 'CSC 2016-cı ildən etibarən dərmanların ümumi alış və satış lisenziyası ilə fəaliyyət göstərir.',
    'about.values.subtitle': 'CSC — Müştərilər, Həllər və Qayğı üzərində qurulub.',
    'about.values.intro': 'CSC bütün işimizin dayandığı üç balinadır. MÜŞTƏRİLƏR, HƏLLƏR və QAYĞI.',
    'about.values.gear': 'Bu konsepsiyaların nəql etdiyi və hərəkətlərimizə gətirdiyi nəhəng mexanizmdəki əsas dişli çarxlara bənzəyir.',
    'about.values.clients.title': 'Müştərilər',
    'about.values.clients.desc': 'Sözümüzü saxlayırıq — iş və tərəfdaşların mənafelərini öz mənafelərimizdən üstün tuturuq, məsuliyyətlə vədi veririk. Hər bir komanda üzvümüzün verdiyi sözdür.',
    'about.values.solutions.title': 'Həllər',
    'about.values.solutions.desc': 'Həllər tapırıq — müəssisəkarlığı, yaradıcılığı və innovasiyanı birləşdiririk, problemlərin qarşısında təşəbbüs göstəririk, maraqlı və iddialı hədəflər qoyuruq.',
    'about.values.care.title': 'Qayğı',
    'about.values.care.desc': 'Məhsullarımızın istehlakçılarına qayğı göstəririk — məhsullarımız üzrə ekspert biliklərimiz var, xəstələrin ehtiyaclarını anlayırıq. Xəstələrin problemlərini daha yaxşı həll edən yeni məhsullar axtarırıq.',
    'about.team.title': 'Komandamız',
    'about.team.desc': 'İşə güclü məsuliyyət hissi və şirkəti inkişaf etdirmək arzusu bizi birləşdirir. Hər bir komanda üzvü CSC-nin uğurunun bir hissəsidir.',
    'about.social.title': 'Sosial Məsuliyyət',
    'about.social.desc': 'Ehtiyacı olanlara kömək etmək və sosial layihələri dəstəkləmək öhdəliyimiz olduğuna inanırıq. Səhiyyə təhsilinə dəstək verir, tibbi tədarük layihələrinə töhfə veririk.',
    'about.nav.mission': 'Missiya',
    'about.nav.history': 'Tarix',
    'about.nav.values': 'Dəyərlər',
    'about.nav.team': 'Komanda',
    'about.nav.social': 'Sosial Məsuliyyət',
    'corporate.tab.about': 'Haqqımızda',
    'corporate.tab.mission': 'Missiya',
    'corporate.tab.vision': 'Vizyon',
    'corporate.tab.branches': 'Filiallar',
    'corporate.tab.certificates': 'Sertifikatlar',
    'corporate.tab.team': 'Komanda',
    'corporate.clients.title': 'Müştərilər',
    'corporate.clients.slogan': 'Sözümüzün üstündə dururuq!',
    'corporate.solutions.title': 'Həllər',
    'corporate.solutions.slogan': 'Həll tapırıq!',
    'corporate.care.title': 'Qayğı',
    'corporate.care.slogan': 'Qayğı göstəririk!',
    'corporate.clients.desc': 'Sözümüzün üstündə dururuq – biznes və tərəfdaşların mənafelərini öz mənafelərimizdən üstün tuturuq, məsuliyyətlə söz veririk\n\nSözümüz, komandanın hər bir üzvünün verdiyi sözdür.\n\nDüzgünük və problemi gizlətmərik.\n\nYalnız etibarlı məlumat təqdim edirik.\n\nMüştəri bir həkim, bir aptek, bir tərəfdaş, bir istehsalçıdır.',
    'corporate.solutions.desc': 'Həll tapırıq – müəssisəkarlığı, yaradıcılığı və innovasiyanı birləştiririk, problemin qarşısında təşəbbüs göstəririk, maraqlı və iddialı məqsədlər qoyuruq, özümüzü, işimizi və proseslərimizi inkişaf etdirməyə çalışırıq.\n\nKomanda şəklində problemləri həll edirik.\n\nBaşqalarının göstərdiyi səyləri tanıyırıq. Yeni bir şey yaratma cəhdlərini təşviq edirik. Başqalarının səhvlərini bağışlayırıq, özümüzə qarşı amansız oluruq.',
    'corporate.care.desc': 'Məhsullarımızın istehlakçılarına qayığı göstəririk – məhsullarımız üzrə ekspert biliyimiz var, xəstələrin ehtiyaclarını anlayırıq.\n\nXəstələrin problemlərini daha yaxşı həll edən yeni məhsullar axtarırıq və onların əlçatanlığını təmin edirik.\n\nHəkimlərin təlimini, məhsullarımızın təhlükəsiz və rahat istifadəsini önəmsirik.\n\nXəstələr və həkimlər üçün xidmətlər inkişaf etdiririk.',
    'corporate.mission.title': 'Missiyamız',
    'corporate.mission.body': 'Yüksək keyfiyyətli, Türkiyə mənşəli dərmanları səhiyyə müəssisələrinə dünya üzrə etibarlılıq, sürət və tam tənzimləyici uyğunluqla çatdırmaq. Mərkəzi Asiya, Qafqaz, Afrika və daha irəli ən etibarlı dərman təchizat tərəfdaşı olmağı hədəfləyirik.',
    'corporate.vision.title': 'Vizyonumuz',
    'corporate.vision.body': 'Türk dərman istehsalçılarını qlobal bazarlarla birləşdirən aparıcı bir dərman paylanma şəbəkəsi olmaq. 2028-ci ilədək dörd qitədə tam inteqrasiya edilmiş soyuducu zəncir, rəqəmsal təchizat platforması və yerli tərəfdaşlıqlarla 50+ ölkədə fəaliyyət göstərməyi hədəfləyirik.',
    'corporate.team.title': 'Rəhbərlik Komandamız',
    'corporate.team.body': 'Komandamız təcrübəli əczaçılar, logistika mütəxəssisləri və tənzimləyici məsləhətçilərdən ibarətdir. 10 ildən çox dərman təchizat zənciri təcrübəsi ilə hər göndərmənin ən yüksək keyfiyyət standartlarını qarşılamasını təmin edirik.',
    'corporate.title': 'Korporativ',
    'corporate.subtitle': 'CSC Ecza Deposu haqqında ətraflı məlumat əldə edin.',


  },
};

/* ──────────────────────────────────────────────
   Context
   ────────────────────────────────────────────── */

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    localStorage.removeItem('csc-language-v3');
    const saved = localStorage.getItem('csc-language-v4');
    return (saved as Language) || 'en';
  });

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('csc-language-v4', lang);
    document.documentElement.lang = lang === 'tr' ? 'tr' : lang === 'ru' ? 'ru' : lang === 'kz' ? 'kk' : lang === 'az' ? 'az' : 'en';
  }, []);

  const t = useCallback(
    (key: string): string => {
      return translations[language][key] || key;
    },
    [language]
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useTranslation() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useTranslation must be used within LanguageProvider');
  }
  return context;
}
